In [ ]:
from src.proj import PATH

paths = list(PATH.model_nn.rglob('*.yaml'))
paths

[PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gru_day/configs/model.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gru_day/configs/schedule.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gru_day/configs/algo.gru.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gruRTN_day/configs/model.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gruRTN_day/configs/schedule.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gruRTN_day/configs/algo.gru.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gru_avg/configs/model.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gru_avg/configs/schedule.yaml'),
 PosixPath('/Users/mengkjin/workspace/learndl/models/nn/gru@gru_avg/configs/algo.gru.yaml')]

In [4]:
PATH.read_yaml(paths[0])

{'callbacks.BatchDisplay': {},
 'callbacks.CallbackTimer': {},
 'callbacks.DetailedAlphaAnalysis': {},
 'callbacks.EarlyExitRetrain': {'earliest': 10,
  'lr_multiplier': [1, 0.1, 10, 0.01, 100, 1],
  'max_attempt': 4},
 'callbacks.EarlyStoppage': {'patience': 20},
 'callbacks.NanLossRetrain': {'max_attempt': 4},
 'callbacks.LearnRateReset': {'num_reset': 2,
  'recover_level': 1.0,
  'speedup2x': True,
  'trigger': 40},
 'callbacks.StatusDisplay': {},
 'callbacks.ValidationConverge': {'eps': 1e-05, 'patience': 5},
 'conditional.short_test.callbacks.DetailedAlphaAnalysis': {'tasks': ['factor',
   't50']},
 'conditional.short_test.input.filter.date': '20220101-20240930',
 'conditional.short_test.input.filter.secid': 'random.200',
 'conditional.short_test.model.beg_date': 20240701,
 'conditional.short_test.model.end_date': 20240930,
 'conditional.short_test.model.window': 240,
 'conditional.short_test.train.max_epoch': 3,
 'conditional.transformer.callbacks.LearnRateReset': {'num_reset': 1,
  'recover_level': 1.0,
  'speedup2x': True,
  'trigger': 60},
 'env.allow_tf32': True,
 'env.detect_anomaly': False,
 'env.mem_storage': True,
 'env.precision': 'float',
 'env.random_seed': None,
 'env.short_test': False,
 'input.combo.types': ['data', 'factor'],
 'input.data.prenorm.day.divlast': True,
 'input.data.prenorm.day.histnorm': True,
 'input.data.types': 'day',
 'input.factor.types': {'fundament': ['quality']},
 'input.filter.date': None,
 'input.filter.secid': None,
 'input.hidden.types': ['gru_day_V0.0.best', 'gru_day_V0.1.best'],
 'input.sequence.lens': {'day': 30,
  'factor': 1,
  'hidden': 1,
  'indus': 30,
  'style': 30},
 'input.sequence.steps': {'data': 1, 'day': 1, 'factor': 1, 'hidden': 1},
 'input.type': 'data',
 'model.beg_date': 20170103,
 'model.end_date': 99991231,
 'model.interval': None,
 'model.interval.boost': 20,
 'model.interval.nn': 120,
 'model.labels': ['std_lag1_10'],
 'model.module': 'nn@gru',
 'model.module.boost': 'xgboost',
 'model.module.boost.optuna': False,
 'model.module.boost.optuna.trials': 10,
 'model.module.factor': None,
 'model.module.nn': 'gru',
 'model.module.nn.boost_head': False,
 'model.module.nn.boost_head.boost': 'lgbm',
 'model.name': 'gru_day',
 'model.submodels': ['best', 'swalast', 'swabest'],
 'model.window': None,
 'model.window.boost': 240,
 'model.window.nn': 2400,
 'train.batch_size': 10000,
 'train.callbacks': ['StatusDisplay',
  'BasicTestResult',
  'DetailedAlphaAnalysis',
  'EarlyStoppage',
  'EarlyExitRetrain',
  'NanLossRetrain',
  'ValidationConverge'],
 'train.criterion.accuracy': {'spearman': {'which_label': [0],
   'which_output': [0]}},
 'train.criterion.loss': {'ccc': {},
  'hidden_corr': {'alpha': 0.0},
  'hidden_corr_deprecated': {'alpha': 0.001}},
 'train.criterion.multilosses': {'name': 'hybrid',
  'params': {'dwa': {'tau': 2},
   'ewa': {},
   'gls': {},
   'hybrid': {'phi': None, 'tau': 2},
   'ruw': {'phi': None},
   'rws': {}}},
 'train.criterion.weight.fit': 'equal',
 'train.criterion.weight.test': 'equal',
 'train.dataloader.sample_method': 'sequential',
 'train.dataloader.shuffle_option': 'epoch',
 'train.dataloader.train_ratio': 0.8,
 'train.fitting_step': 5,
 'train.max_epoch': 200,
 'train.skip_horizon': 20,
 'train.trainer.gradient.clip_value': 10.0,
 'train.trainer.learn_rate.base': 0.005,
 'train.trainer.learn_rate.transfer_multiplier.decoder': 1.0,
 'train.trainer.learn_rate.transfer_multiplier.encoder': 0.1,
 'train.trainer.optimizer.name': 'Adam',
 'train.trainer.optimizer.param': {},
 'train.trainer.scheduler.name': 'cycle',
 'train.trainer.scheduler.param.base_lr': 1e-07,
 'train.trainer.scheduler.param.step_size_up': 4,
 'train.trainer.transfer': False}

In [26]:
from src.proj import PATH , Logger

from typing import Callable , TypeAlias

DictLoader : TypeAlias = Callable[[] , dict] | dict

class ModelConfigModifier:
    @classmethod
    def rename_ResetOptimizer(cls , key : str , config : DictLoader):
        if not key.endswith('.model'):
            return config
        if not isinstance(config , dict):
            config = config()
        old_name = 'callbacks.ResetOptimizer'
        new_name = 'callbacks.LearnRateReset'
        default_value = {
            'num_reset': 2,
            'recover_level': 1.0,
            'speedup2x': True,
            'trigger': 40
        }
        if old_name in config:
            value = config.pop(old_name)
            Logger.success(f'{key}.{old_name} has been removed')
        else:
            value = default_value
        if new_name not in config:
            config[new_name] = value
            Logger.success(f'{key}.{new_name} has been added')

        for name in config:
            if 'ResetOptimizer' in name:
                new_name = name.replace('ResetOptimizer' , 'LearnRateReset')
                config[new_name] = config.pop(name)
                Logger.success(f'{key}.{name} has been renamed to {new_name}')
        return config

    @classmethod
    def add_LearnRateReset(cls , key : str , config : DictLoader):
        if not key.endswith('.model'):
            return config
        if not isinstance(config , dict):
            config = config()
        if 'LearnRateReset' not in config['train.callbacks']:
            config['train.callbacks'].append('LearnRateReset')
            Logger.success(f'{key}.train.callbacks lacks LearnRateReset , added')
        return config

    @classmethod
    def rename_lamb(cls , key : str , config : DictLoader):
        if not key.endswith(('.model' , '.schedule')):
            return config
        if not isinstance(config , dict):
            config = config()
        if 'train.criterion.loss' not in config:
            return config
        for loss_name , loss_kwargs in config['train.criterion.loss'].items():
            if 'lamb' in loss_kwargs:
                assert 'alpha' not in loss_kwargs, f'{loss_name} already has alpha key : {loss_kwargs}'
                config['train.criterion.loss'][loss_name]['alpha'] = loss_kwargs.pop('lamb')
                Logger.success(f'{key}.train.criterion.loss.{loss_name} has lamb key , renamed to alpha')
        return config

class ModelConfigsBatchModifier:
    def __init__(self):
        self.root = PATH.model
        self.task_list : list[Callable[[str , DictLoader] , DictLoader]] = [
            getattr(ModelConfigModifier , name) for name in dir(ModelConfigModifier) if not name.startswith('_')
        ]

    def load_config(self) -> dict:
        return PATH.read_yaml(self.current_path)

    def dump_config(self , config : DictLoader):
        if isinstance(config , dict):
            PATH.dump_yaml(config , self.current_path , overwrite = True)

    def batch_modify(self):
        for path in self.root.rglob('*.yaml'):
            self.current_path = path
            config = self.load_config
            for task in self.task_list:
                config = task(f'{path.parent.parent.stem}.{path.stem}' , config)
            if isinstance(config , dict):
                self.dump_config(config)
                
modifier = ModelConfigsBatchModifier()
modifier.batch_modify()

In [32]:
class ModelConfigsInspecter:
    def __init__(self):
        self.model_root = PATH.model
        self.config_root = PATH.conf

    def iter_configs(self):
        for self.current_path in self.model_root.rglob('*.yaml'):
            yield self.current_path
        for self.current_path in self.config_root.rglob('*.yaml'):
            yield self.current_path

    def inspect_key_values(self , warning_list : list[str]):
        for path in self.iter_configs():
            config = PATH.read_yaml(path)
            self.inspect_object(config , warning_list)

    def inspect_object(self , obj , warning_list : list[str] , full_match : bool = False):
        if isinstance(obj , str):
            if obj in warning_list:
                Logger.alert2(f'{self.current_path.stem} has {obj} (full_match)')
            elif not full_match and any(warning in obj for warning in warning_list):
                Logger.alert1(f'{self.current_path.stem} has {obj} (partial_match)')
            return
        if isinstance(obj , dict):
            for key , value in obj.items():
                self.inspect_object(key , warning_list , full_match = False)
                self.inspect_object(value , warning_list , full_match = True)
            return
        if isinstance(obj , list):
            for item in obj:
                self.inspect_object(item , warning_list , full_match = True)
            return
inspecter = ModelConfigsInspecter()
inspecter.inspect_key_values(['ResetOptimizer' , 'lamb'])

Caution : algo.lgbm has reg_lambda (partial_match)
Caution : custom has lambda (partial_match)
Caution : default has lambda (partial_match)
Caution : lgbm has lambda_l2 (partial_match)
Caution : hidden_aggregator has lambda_l2 (partial_match)
Caution : xgboost has reg_lambda (partial_match)
Caution : lgbm has reg_lambda (partial_match)

In [8]:
dir(ModelConfigModifier)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'add_LearnRateReset',
 'rename_ResetOptimizer',
 'rename_lamb']

In [ ]:
description = """
Run top fmp test on factors resolved via ``get_factor``.

Args:
  names : Factor name(s) to test. If '' or 'random', a random factor will be used; Factor name(s) will be split by ','.
  factor_type : Factor type ('factor' or 'pred').
  benchmark : Benchmark name(s) to test. If 'defaults', will use all default benchmarks. If a string, will be split by ','.
  start : Start date for the test.
  end : End date for the test.
  step : Step size for the test.
  write_down : Whether to write down the test results.
  display_figs : Whether to display the test figures.
  indent : Indent level for the test.
  vb_level : Verbosity level for the test.
"""
param_keys = ['names', 'factor_type', 'benchmark', 'start', 'end', 'step', 'write_down', 'display_figs', 'indent', 'vb_level']

helps = {}
lines = [line.strip() for line in description.split('\n') if line.strip()]
args_start = False
for line in lines:
    if line.lower().replace(' ', '').removesuffix(':') == 'args':
        print('here')
        args_start = True
    if line.lower().replace(' ', '').removesuffix(':') in ['return', 'returns' , '[apiinteraction]']:
        break
    if args_start and ':' in line:
        key , value = line.split(':', 1)
        if key.strip() in param_keys:
            helps[key.strip()] = value.strip()

here

In [ ]:
from functools import wraps
from typing import Callable
class A:
    _trainer : 'A | None' = None
    def __new__(cls , *args , **kwargs):
        if cls._trainer is None:
            obj = super().__new__(cls)
            TrainerHookWrapper.wrap(obj)
            cls._trainer = obj
        return cls._trainer

    def test(self):
        print('test')

def test_wrap(func : Callable):
    @wraps(func)
    def wrapper(self , *args , **kwargs):
        print('wrapper')
        return func(self , *args , **kwargs)
    return wrapper


test_wrap(A.test)(A())

wrapper
test

In [ ]:
from typing import Any
a : tuple[int , Any , ...] = (1 , 'b' , 'c')

['Run top fmp test on factors resolved via ``get_factor``.',
 'Args:',
 "names : Factor name(s) to test. If '' or 'random', a random factor will be used; Factor name(s) will be split by ','.",
 "factor_type : Factor type ('factor' or 'pred').",
 "benchmark : Benchmark name(s) to test. If 'defaults', will use all default benchmarks. If a string, will be split by ','.",
 'start : Start date for the test.',
 'end : End date for the test.',
 'step : Step size for the test.',
 'write_down : Whether to write down the test results.',
 'display_figs : Whether to display the test figures.',
 'indent : Indent level for the test.',
 'vb_level : Verbosity level for the test.']

In [12]:
import torch
torch.load('models/nn/gru@gru_avg/archive/0/20241129/best/state_dict.pt')

OrderedDict([('encoder.mod_list.0.fc_enc_in.0.weight',
              tensor([[-2.0684e-01,  1.3455e-02,  4.6457e-01, -3.7192e-01, -3.0588e-01,
                        6.6647e-01],
                      [ 1.1447e-01, -1.1956e+00, -5.4807e-01, -3.2060e-01, -6.0345e-02,
                        1.7907e-01],
                      [ 5.4200e-02,  4.7296e-01,  5.5665e-01, -1.0737e-01, -6.6709e-01,
                       -1.8662e-01],
                      [ 3.1615e-01,  5.5738e-01,  2.8819e-02, -6.8724e-01, -8.1001e-04,
                        6.6882e-02],
                      [ 4.0360e-01,  1.6652e-01, -4.8485e-01, -1.1170e-01,  3.8480e-01,
                       -6.4656e-01],
                      [-2.8048e-01,  4.0541e-01,  3.1246e-01,  1.0762e-01, -4.6153e-01,
                        5.2263e-02],
                      [-2.5643e-01, -4.7854e-01,  3.1609e-01,  9.6570e-02,  1.2791e-01,
                       -1.8591e-01],
                      [ 5.5262e-01,  2.8363e-01, -1.3623e-02, -5.0103e-01, -2.8883e-01,
                        2.6381e-01],
                      [ 1.4588e-01,  1.4132e-01,  2.7316e-01, -3.0287e-01, -2.2982e-01,
                       -2.2545e-01],
                      [-7.6319e-02, -1.0014e-01,  1.3759e-01,  4.0476e-01, -2.6999e-01,
                       -3.5915e-01],
                      [ 2.9271e-01, -3.6788e-01, -2.4348e-01,  3.5796e-01, -1.9928e-01,
                       -1.8211e-02],
                      [-3.0869e-01,  5.2436e-01,  4.0602e-01,  1.5913e-01,  1.0608e-01,
                       -1.7116e-01],
                      [ 4.2233e-01, -1.6204e-01, -2.0621e-01, -2.6690e-01,  2.0963e-01,
                       -4.6431e-02],
                      [-8.1395e-02, -1.2667e-01,  1.9377e-01,  1.4654e-02,  1.8737e-01,
                        5.5961e-01],
                      [ 4.4433e-01, -4.8186e-01, -3.6037e-01,  3.6345e-01,  1.2991e-01,
                       -5.9568e-02],
                      [-1.1162e-01,  1.4935e-01,  2.0942e-01,  2.7659e-01,  1.0964e-01,
                        2.8635e-01],
                      [ 2.1464e-01, -4.1682e-02,  2.7132e-01,  5.6957e-02,  2.3825e-01,
                       -4.1129e-01],
                      [-3.0879e-01,  2.3384e-01, -6.0798e-01,  4.8931e-01,  3.8409e-01,
                       -2.6299e-01],
                      [ 1.9809e-01, -9.3479e-02,  1.1395e-01, -4.1624e-01,  8.0967e-02,
                        3.6028e-02],
                      [-1.5400e-03, -4.7170e-01,  4.9063e-02,  2.3972e-01, -3.3656e-01,
                        1.9813e-01],
                      [ 5.7592e-02, -9.8240e-01, -8.5688e-01, -4.7246e-01, -5.0990e-01,
                        5.2757e-02],
                      [ 3.3110e-01, -4.5985e-01, -3.5619e-01,  2.7178e-01,  7.7295e-02,
                        6.8580e-03],
                      [ 3.3239e-01,  2.7479e-01, -6.4901e-02,  3.5470e-01, -2.6354e-01,
                       -6.0742e-01],
                      [ 2.4013e-01,  1.5516e-01,  5.7330e-01, -5.1836e-01, -3.3347e-01,
                       -3.8553e-01],
                      [ 1.9839e-01,  4.4911e-01,  3.6369e-01, -4.8169e-01, -1.0943e-01,
                       -5.2004e-01],
                      [-2.9055e-01, -3.9995e-01,  3.6596e-01,  3.1529e-02,  1.0333e-01,
                       -4.1856e-01],
                      [ 2.3258e-01, -1.4091e-01,  4.3769e-01, -3.7419e-01, -1.6143e-01,
                        4.9049e-02],
                      [ 3.3139e-01, -3.5651e-01, -3.1534e-01,  4.4134e-01,  9.1896e-02,
                       -1.5521e-01],
                      [ 9.1870e-02,  2.3032e-01,  3.9195e-01, -2.0801e-01, -3.0491e-01,
                        3.9313e-01],
                      [-2.7847e-02, -4.2880e-01, -1.2653e-01, -5.5678e-02,  2.5863e-01,
                       -3.1722e-01],
                      [-5.4462e-02,  2.0757e-02,  9.7850e-03,  4.5612e-01, -1.7205e-01,
                       -1.0984e-01],
                      [ 4.9326e-01, -2.1344e-01, -3.7831e-01,  5.3218e-03,  3.5445e-02,
                       -4.9193e-01]])),
             ('encoder.mod_list.0.fc_enc_in.0.bias',
              tensor([ 0.0197, -0.3326,  0.0576, -0.2407, -0.2911, -0.1515,  0.0013, -0.2837,
                      -0.0468,  0.1690, -0.2258, -0.3248, -0.0051,  0.4698,  0.2618,  0.1632,
                      -0.2630, -0.0116,  0.2964, -0.5347,  0.2543, -0.1043, -0.2091, -0.0231,
                       0.2602, -0.3000,  0.0028,  0.1687,  0.2562, -0.5032, -0.0220, -0.2400])),
             ('encoder.mod_list.0.fc_rnn.gru.weight_ih_l0',
              tensor([[-0.1117,  0.0660,  0.2819,  ...,  0.1703, -0.2010,  0.2464],
                      [ 0.1155, -0.0412, -0.0064,  ..., -0.2293, -0.0382, -0.1723],
                      [-0.3197, -0.1752,  0.1751,  ..., -0.0076, -0.0286, -0.0505],
                      ...,
                      [-0.1435,  0.3790, -0.1359,  ...,  0.1614,  0.0186,  0.0427],
                      [ 0.1706,  0.0139, -0.0720,  ..., -0.2629,  0.1627,  0.1670],
                      [-0.0466,  0.1542, -0.0114,  ..., -0.1624,  0.0234,  0.0379]])),
             ('encoder.mod_list.0.fc_rnn.gru.weight_hh_l0',
              tensor([[-0.3891, -0.1787, -0.1123,  ..., -0.1968, -0.1754,  0.1098],
                      [-0.1733,  0.1704,  0.1214,  ..., -0.2420, -0.1428, -0.0573],
                      [-0.0160,  0.2290, -0.2003,  ..., -0.0438, -0.3221,  0.0620],
                      ...,
                      [-0.0670, -0.0615, -0.0583,  ...,  0.0179,  0.0413, -0.0153],
                      [ 0.0437, -0.2266,  0.1126,  ..., -0.2446, -0.2397, -0.1279],
                      [-0.1082,  0.1628, -0.1008,  ...,  0.0958, -0.2775, -0.0477]])),
             ('encoder.mod_list.0.fc_rnn.gru.bias_ih_l0',
              tensor([-0.1247, -0.0544, -0.2686,  0.0363,  0.1996, -0.0107, -0.2334,  0.1038,
                      -0.0536, -0.1225,  0.0139, -0.0881, -0.0373,  0.0637,  0.0998, -0.2683,
                       0.0408,  0.1240, -0.1675,  0.0728, -0.2209, -0.0402, -0.2538,  0.0579,
                      -0.1639,  0.0735, -0.0553,  0.2897,  0.1217,  0.0405, -0.1071, -0.0189,
                       0.1747, -0.0178,  0.0892,  0.3461,  0.2020, -0.2548, -0.1658, -0.3412,
                       0.1738,  0.3913, -0.0099,  0.1538,  0.0761,  0.2753,  0.1582,  0.1387,
                       0.1846, -0.0356,  0.1004, -0.1022,  0.0726,  0.2942,  0.4630, -0.1085,
                       0.1829,  0.2530,  0.1358,  0.0425,  0.2114,  0.4282, -0.1472,  0.1694,
                      -0.0019,  0.0754, -0.0045,  0.0420, -0.0588,  0.0909, -0.2038, -0.0564,
                      -0.1936, -0.0102, -0.0056, -0.0345,  0.1975,  0.0414, -0.1509,  0.0098,
                       0.3189,  0.1107, -0.1796, -0.2335, -0.0367,  0.0380,  0.0922,  0.0789,
                       0.2339,  0.2509,  0.0266, -0.0277,  0.0478, -0.3571, -0.1100,  0.1041])),
             ('encoder.mod_list.0.fc_rnn.gru.bias_hh_l0',
              tensor([ 0.0427,  0.0277, -0.3022, -0.0937,  0.0807, -0.1240, -0.1620, -0.0735,
                      -0.1546, -0.0613,  0.0181,  0.0528, -0.0916,  0.0069,  0.0580, -0.0531,
                       0.1949,  0.0627, -0.1436, -0.0488, -0.0570, -0.3427, -0.0791, -0.0915,
                      -0.2287,  0.0483, -0.0258,  0.0995,  0.0440,  0.2038, -0.0281, -0.0776,
                       0.0440,  0.1318,  0.0472,  0.2161,  0.1077, -0.1450, -0.1179, -0.3499,
                       0.2434,  0.4806,  0.0286,  0.2556, -0.1460,  0.0575,  0.4098,  0.2706,
                       0.1164, -0.0666, -0.0270,  0.0530, -0.0590,  0.3061,  0.3110, -0.1705,
                      -0.0942,  0.3474,  0.2459,  0.2022,  0.0354,  0.4454, -0.2442,  0.2034,
                       0.1778,  0.1144, -0.1318, -0.0462,  0.0205,  0.0626,  0.0653, -0.0487,
                       0.0216,  0.0808,  0.0620,  0.1325,  0.0530,  0.1542,  0.1213,  0.1238,
                       0.1839, -0.0804,  0.0117, -0.2484, -0.0121, -0.0232,  0.1005, -0.0019,
                      -0.0558,  0.1790,  0.2544, -0.0525,  0.1511, -0.3328, -0.0247,  0.2042])),
             ('encoder.mod_list.0.fc_rnn.gru.weight_ih_l1',
              tensor([[ 0.1425, -0.0496,  0.1704,  ..., -0.1805, -0.3255, -0.1305],
                      [-0.0123, -0.1538,  0.0818,  ..., -0.1702, -0.0498, -0.1002],
                      [ 0.2666, -0.0444, -0.2621,  ...,  0.0570,  0.0681, -0.3070],
                      ...,
                      [ 0.0022,  0.1675, -0.1087,  ..., -0.1046,  0.0279, -0.0060],
                      [-0.0262, -0.0683,  0.1713,  ...,  0.1200, -0.1400,  0.1222],
                      [ 0.1667, -0.1797,  0.0810,  ..., -0.2934, -0.0999, -0.0832]])),
             ('encoder.mod_list.0.fc_rnn.gru.weight_hh_l1',
              tensor([[-0.0766, -0.1927,  0.0883,  ..., -0.3824,  0.1158,  0.2175],
                      [-0.0302, -0.4284,  0.2149,  ..., -0.1869,  0.0575,  0.1240],
                      [ 0.1421,  0.0249,  0.1178,  ...,  0.2230, -0.1484,  0.0923],
                      ...,
                      [-0.0060,  0.1389,  0.0452,  ..., -0.2890, -0.0948, -0.0141],
                      [ 0.1276,  0.0401,  0.0676,  ...,  0.1831,  0.2230, -0.0796],
                      [ 0.1074, -0.1173,  0.1452,  ..., -0.0718,  0.0136, -0.0393]])),
             ('encoder.mod_list.0.fc_rnn.gru.bias_ih_l1',
              tensor([-0.1297, -0.1450, -0.3388, -0.3050,  0.0708, -0.2563, -0.0286, -0.2512,
                      -0.1858, -0.2053, -0.0894,  0.0974, -0.1001, -0.1763, -0.1900, -0.2542,
                      -0.0560,  0.0079,  0.0796,  0.0208, -0.1352, -0.1529, -0.0426, -0.0882,
                       0.0317, -0.2337,  0.1772, -0.0953, -0.1878, -0.0668, -0.0942, -0.1892,
                       0.1371,  0.1035,  0.2598, -0.1633, -0.2656,  0.0151,  0.1764, -0.1503,
                       0.0851, -0.0704,  0.1351, -0.1307,  0.2117,  0.1028,  0.3352, -0.0920,
                       0.5252, -0.0011,  0.3017,  0.1921,  0.1552,  0.3798,  0.0782,  0.5256,
                       0.3129,  0.0440,  0.1705,  0.3499,  0.0662,  0.0935,  0.5056,  0.0658,
                       0.1576,  0.0116, -0.2228, -0.0645, -0.0100,  0.1058,  0.1423, -0.2594,
                       0.1598, -0.0832, -0.1508,  0.0019, -0.0780, -0.0550,  0.1303,  0.1086,
                       0.1445, -0.1238,  0.2254,  0.1542,  0.1689,  0.0257, -0.0707, -0.0073,
                       0.0370, -0.0291, -0.1776,  0.0987,  0.1035,  0.1078, -0.2191, -0.0201])),
             ('encoder.mod_list.0.fc_rnn.gru.bias_hh_l1',
              tensor([-0.2475,  0.0083, -0.1235,  0.0023, -0.0821, -0.1063,  0.0578, -0.2660,
                      -0.4063, -0.0087, -0.2160,  0.1207, -0.2024, -0.1797, -0.1109, -0.0816,
                      -0.0762, -0.2552, -0.1853, -0.1960, -0.1843, -0.2508, -0.1153,  0.0175,
                      -0.1341, -0.1814,  0.0272, -0.0301, -0.1974, -0.0424, -0.1879, -0.2723,
                       0.1192,  0.1639,  0.4284, -0.1628, -0.2592,  0.2460,  0.3407,  0.0013,
                       0.1722, -0.3027,  0.0569,  0.0996,  0.2619,  0.2325,  0.0528,  0.1532,
                       0.3227,  0.0093,  0.4852,  0.3182,  0.0375,  0.3098,  0.0553,  0.4388,
                       0.0629, -0.0068,  0.2341,  0.0428,  0.0931,  0.2534,  0.4695,  0.3750,
                       0.1683,  0.1996, -0.0991,  0.0071, -0.0990, -0.0219,  0.0741, -0.0808,
                       0.0527,  0.1016, -0.0289,  0.1697,  0.0315,  0.1399,  0.0910, -0.0912,
                       0.0198,  0.0830,  0.0292,  0.1811,  0.0204, -0.1076, -0.0756,  0.0662,
                      -0.0643,  0.0535, -0.1141,  0.0063,  0.1185,  0.0536,  0.0886,  0.0080])),
             ('decoder.mod_list.0.fc_dec_mlp.0.0.weight',
              tensor([[ 0.0471, -0.1580,  0.0736,  ...,  0.0679,  0.0750, -0.1383],
                      [-0.2074, -0.3444,  0.2259,  ..., -0.1263,  0.0825,  0.2095],
                      [ 0.1684,  0.1860, -0.0641,  ...,  0.0759,  0.1219,  0.2205],
                      ...,
                      [-0.0577,  0.0301,  0.1541,  ...,  0.3420,  0.0204,  0.0343],
                      [ 0.1046,  0.0468,  0.0039,  ..., -0.0289, -0.0488, -0.0721],
                      [-0.1580, -0.1266,  0.2162,  ..., -0.1414,  0.2282, -0.0435]])),
             ('decoder.mod_list.0.fc_dec_mlp.0.0.bias',
              tensor([-0.0301, -0.1963,  0.1144, -0.0409,  0.1282,  0.0651, -0.0645, -0.2939,
                       0.0540,  0.0661,  0.0812,  0.0739, -0.0151, -0.0050, -0.1387, -0.0232,
                      -0.0763, -0.1105,  0.1005,  0.1139,  0.0167, -0.1193, -0.0923,  0.0960,
                       0.0759, -0.0973, -0.0339, -0.0426,  0.1709, -0.1368,  0.0391, -0.2899])),
             ('decoder.mod_list.0.fc_dec_mlp.1.0.weight',
              tensor([[ 0.0624, -0.0821,  0.2807,  ..., -0.1689,  0.2619,  0.0473],
                      [ 0.1409, -0.0031,  0.0719,  ...,  0.0131, -0.1477, -0.1091],
                      [ 0.0354,  0.1401,  0.0723,  ...,  0.0735, -0.0118,  0.1470],
                      ...,
                      [-0.0038,  0.1252,  0.0357,  ...,  0.3435,  0.0750,  0.0646],
                      [ 0.0976,  0.2178, -0.1743,  ...,  0.0580, -0.0310,  0.1329],
                      [ 0.0351,  0.0087,  0.1800,  ...,  0.0855,  0.1231, -0.0628]])),
             ('decoder.mod_list.0.fc_dec_mlp.1.0.bias',
              tensor([-0.0705,  0.0729,  0.1644,  0.0869,  0.0907,  0.0641,  0.1346,  0.0600,
                       0.1555,  0.0228,  0.1269,  0.1162,  0.1414,  0.0455, -0.2477, -0.0611,
                       0.0404, -0.0550,  0.1962,  0.1144,  0.1062,  0.0899,  0.0398,  0.0897,
                      -0.0188,  0.1815, -0.2050, -0.1148,  0.1621,  0.0113,  0.1419,  0.1053])),
             ('decoder.mod_list.0.fc_hid_out.weight',
              tensor([[ 2.8610e-01, -1.6771e-01,  5.5432e-02,  ...,  1.6656e-01,
                       -3.1377e-02,  6.5205e-02],
                      [-9.8291e-02,  2.2899e-01,  1.3289e-01,  ..., -5.6635e-02,
                        4.8346e-02, -4.0188e-02],
                      [ 1.2475e-01, -7.2021e-02,  1.2160e-05,  ...,  1.2146e-01,
                        1.3683e-01, -1.0894e-01],
                      ...,
                      [ 2.5259e-01,  9.9726e-02,  3.8558e-02,  ..., -1.2363e-01,
                       -7.0963e-02,  1.0122e-01],
                      [-2.7486e-01,  2.1679e-01,  1.5015e-01,  ..., -1.9328e-01,
                       -5.7790e-02, -1.8677e-01],
                      [-1.1720e-01, -2.5884e-02, -6.8765e-02,  ..., -2.0412e-01,
                        1.6556e-01, -1.0038e-01]])),
             ('decoder.mod_list.0.fc_hid_out.bias',
              tensor([ 0.0931,  0.0958,  0.0020,  0.0688, -0.0407,  0.1523, -0.0494,  0.0740,
                      -0.1639,  0.1069, -0.1706,  0.1396,  0.0413, -0.0905,  0.1554,  0.1061,
                       0.0612,  0.1290,  0.0941,  0.1534,  0.0312,  0.0984, -0.1203, -0.0986,
                      -0.0240,  0.0337, -0.1632, -0.1351,  0.0659, -0.1501,  0.1458,  0.0411])),
             ('mapping.mod_list.0.fc_map_out.0.weight',
              tensor([[-0.1348,  0.1474,  0.0036, -0.1237,  0.2255, -0.0485, -0.1152, -0.0895,
                       -0.1006,  0.1470,  0.0172,  0.0258, -0.1922, -0.1434,  0.0916, -0.1721,
                       -0.0061, -0.0976, -0.0958, -0.0966,  0.1705, -0.0225, -0.2125,  0.0136,
                        0.0772,  0.0376, -0.0350,  0.0550,  0.0059, -0.1476,  0.1934,  0.1573]])),
             ('mapping.mod_list.0.fc_map_out.0.bias', tensor([-0.1386])),
             ('mapping.mod_list.0.fc_map_out.1.weight', tensor([1.0000])),
             ('mapping.mod_list.0.fc_map_out.1.bias', tensor([0.1661])),
             ('mapping.mod_list.0.fc_map_out.1.running_mean',
              tensor([-1.8735])),
             ('mapping.mod_list.0.fc_map_out.1.running_var',
              tensor([10.1491])),
             ('mapping.mod_list.0.fc_map_out.1.num_batches_tracked',
              tensor(4608))])

In [8]:
import numpy as np
import pandas as pd
a = np.array(a for a in (5 , 1 , 2 , 4 , 3))
a.argmin()

0

In [3]:
a.to_dict('records')

[{'c': 7, 'd': 10}, {'c': 8, 'd': 11}, {'c': 9, 'd': 12}]

In [2]:
from collections import defaultdict
a : dict[int , dict[str , list]] = defaultdict(dict)
a.clear()
'a' in a[0]

False

In [6]:
pool.proxies

{'https://www.bse.cn': ProxyStatsSetURL(https://www.bse.cn,adaptive,refresh_attempt=0/10),
 'https://www.sse.com.cn': ProxyStatsSetURL(https://www.sse.com.cn,adaptive,refresh_attempt=0/10),
 'https://www.szse.cn': ProxyStatsSetURL(https://www.szse.cn,adaptive,refresh_attempt=0/10)}

In [26]:
import pandas as pd
import numpy as np

from typing import Any


pool = pd.DataFrame({'secid': np.random.randint(0, 1000000, size=50), 
                     'indus': np.random.randint(0, 10, size=50), 
                     'alpha': np.random.randn(50)})

init_port = pd.DataFrame({'secid': np.random.choice(pool['secid'], size=10 , replace = False), 
                          'weight': np.random.randn(10)})

buffer_zone = 0.1
stay_num = 8
no_zone = 0.5
indus_slots = 10
n_best = 10

pool.loc[:, 'ind_rank']  = pool.groupby('indus')['alpha'].rank(method = 'first' , ascending = False)
pool.loc[:, 'rankpct']   = pool['alpha'].rank(pct = True , method = 'first' , ascending = True)

pool = pool.merge(init_port , on = 'secid' , how = 'left').sort_values('alpha' , ascending = False)
pool.loc[:, 'selected'] = pool['weight'].astype(float).fillna(0) > 0
pool.loc[:, 'buffered'] = (
    (pool['rankpct'] >= buffer_zone) + (pool['selected'].cumsum() <= stay_num) * (pool['rankpct'] >= no_zone))

stay = pool.query('selected & buffered')

new_pool = pool.query('(secid not in @stay.secid)').merge(stay.groupby('indus')['secid'].count().rename('ind_count') , on = 'indus' , how = 'left')
entry = new_pool.assign(max_ind_rank = indus_slots - new_pool['ind_count'].fillna(0)).\
    query('ind_rank < max_ind_rank').sort_values('alpha' , ascending = False).head(n_best - stay.shape[0])

df = pd.DataFrame({'secid' : np.union1d(stay['secid'] , entry['secid']) , 'weight' : 1})
df

    secid  weight
0   87026       1
1   92220       1
2  244585       1
3  248610       1
4  404240       1
5  410914       1
6  464663       1
7  725616       1
8  815841       1
9  817782       1

In [7]:
entry

,secid,indus,alpha,ind_rank,rankpct,weight,selected,buffered,stay_ind_count,max_ind_rank
0,580999,3,1.993092,2.0,0.98,NaN,False,True,1.0,9.0
1,395957,1,1.863609,1.0,0.96,NaN,False,True,2.0,8.0
2,158281,7,1.635280,1.0,0.94,NaN,False,True,NaN,10.0
3,334736,5,1.506816,1.0,0.92,NaN,False,True,NaN,10.0
4,308209,1,1.444555,2.0,0.90,NaN,False,True,2.0,8.0
5,162291,8,1.301753,1.0,0.88,NaN,False,True,NaN,10.0

In [24]:
import machineid
machineid.id()

'71A41312-74C2-5E3E-94E3-88261EF3E297'

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************