In [3]:
import requests
url = 'https://www.freeproxy.world/?type=https&anonymity=4&country=&speed=1000&port='
r = requests.get(url)
r.text

'<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0, user-scalable=yes" />\n    <title>Free Proxy List https - FreeProxy.World</title>\n    <meta name="keywords" content="Free Proxy World, Free Proxy, HTTP proxy, HTTPS proxy, SOCKS4 proxy, SOCKS5 proxy, Proxy list">\n    <meta name="description" content="Worldwide free proxy list. Free fresh working proxy, including HTTP/SOCKS/SSL">\n    <link rel="stylesheet" href="/css/site.css?v=G49tGwq5sGmELkhx8ty3QPtPFGd-K9RMSd6IxF9GKdo" />\n    <link rel="stylesheet" href="/css/flags.css?v=zITMPjpB4OwDCMkJM7snPmsENJdRBSYU6hPxrykww34">\n    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">\n    \n    <!-- Google Ads -->\n    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2267767860475779" crossorigin="anonymous"></script>\n</head>\n<body>\n    <header>\n        <div class="container">\n            <nav class="navbar">\n                <a class="logo" href="/">\n                    <img src="/img/logo.png" alt="FreeProxy.World">\n                </a>\n                <div class="menu-toggle" id="mobile-menu">\n                    <span>&#9776;</span>\n                </div>\n                <ul class="nav-links" id="nav-links">\n                    <li><a class="active" href="/">Proxy List</a></li>\n                    <li><a class="" href="/Filter/Country">By Country</a></li>\n                    <li><a class="" href="/Filter/Port">By Port</a></li>\n                    <li><a class="" style="color: var(--warning-color);" href="/Promotions">VPN Deals</a></li>\n                    <li><a class="" href="/Donate">Buy Me a Coffee</a></li>\n                </ul>\n            </nav>\n        </div>\n    </header>\n\n    <main class="container">\n        \n<!-- Filter Section -->\n<div class="filter-section">\n    <form action="" method="get">\n        <div class="d-flex" style="flex-wrap: wrap; gap: 20px;">\n            <div class="form-group" style="flex: 1; min-width: 250px;">\n                <label class="form-label">Proxy Type</label>\n                <div class="radio-group">\n                    <input type="radio" id="type_all" name="type" value="" >\n                    <label for="type_all">All</label>\n                    \n                    <input type="radio" id="type_http" name="type" value="http" >\n                    <label for="type_http">HTTP</label>\n                    \n                    <input type="radio" id="type_https" name="type" value="https" checked>\n                    <label for="type_https">HTTPS</label>\n                    \n                    <input type="radio" id="type_socks4" name="type" value="socks4" >\n                    <label for="type_socks4">SOCKS4</label>\n                    \n                    <input type="radio" id="type_socks5" name="type" value="socks5" >\n                    <label for="type_socks5">SOCKS5</label>\n                </div>\n            </div>\n            \n            <div class="form-group" style="flex: 1; min-width: 200px;">\n                <label class="form-label">Anonymity</label>\n                <div class="radio-group">\n                    <input type="radio" id="anon_all" name="anonymity" value="" >\n                    <label for="anon_all">All</label>\n                    \n                    <input type="radio" id="anon_high" name="anonymity" value="4" checked>\n                    <label for="anon_high">High</label>\n                    \n                    <input type="radio" id="anon_no" name="anonymity" value="1" >\n                    <label for="anon_no">No</label>\n                </div>\n            </div>\n        </div>\n\n        <div class="d-flex mt-3" style="flex-wrap: wrap; gap: 15px; align-items: flex-end;">\n            <div class="form-group" style="flex: 2; min-width: 200px;">\n                <label class="form-label">Country</label>\n                <select name="country" class="form-control">\n                    <option value="">All Countries</option>\n                            <option value="US">\n                                United States of America (46470)\n                            </option>\n                            <option value="ID">\n                                Indonesia (1050)\n                            </option>\n                            <option value="DE">\n                                Germany (899)\n                            </option>\n                            <option value="IT">\n                                Italy (30)\n                            </option>\n                            <option value="RO">\n                                Romania (174)\n                            </option>\n                            <option value="KR">\n                                Korea (the Republic of) (152)\n                            </option>\n                            <option value="PL">\n                                Poland (67)\n                            </option>\n                            <option value="AE">\n                                United Arab Emirates (72)\n                            </option>\n                            <option value="ZA">\n                                South Africa (212)\n                            </option>\n                            <option value="SG">\n                                Singapore (1023)\n                            </option>\n                            <option value="CA">\n                                Canada (697)\n                            </option>\n                            <option value="BZ">\n                                Belize (1666)\n                            </option>\n                            <option value="CW">\n                                Curacao (147)\n                            </option>\n                            <option value="AL">\n                                Albania (11)\n                            </option>\n                            <option value="NL">\n                                Netherlands (Kingdom of the) (1190)\n                            </option>\n                            <option value="GB">\n                                United Kingdom of Great Britain and Northern Ireland (2713)\n                            </option>\n                            <option value="BE">\n                                Belgium (1505)\n                            </option>\n                            <option value="RU">\n                                Russian Federation (1225)\n                            </option>\n                            <option value="KZ">\n                                Kazakhstan (584)\n                            </option>\n                            <option value="PH">\n                                Philippines (367)\n                            </option>\n                            <option value="EE">\n                                Estonia (323)\n                            </option>\n                            <option value="AU">\n                                Australia (167)\n                            </option>\n                            <option value="UA">\n                                Ukraine (211)\n                            </option>\n                            <option value="NG">\n                                Nigeria (10)\n                            </option>\n                            <option value="HK">\n                                Hong Kong (158)\n                            </option>\n                            <option value="-">\n                                - (44)\n                            </option>\n                            <option value="EC">\n                                Ecuador (72)\n                            </option>\n                            <option value="EG">\n                                Egypt (25)\n                            </option>\n                            <option value="CH">\n                                Switzerland (12)\n                            </option>\n                            <option value="PY">\n                                Paraguay (21)\n                            </option>\n                            <option value="SE">\n                                Sweden (175)\n                            </option>\n                            <option value="IN">\n                                India (199)\n                            </option>\n                            <option value="TW">\n                                Taiwan (Province of China) (17)\n                            </option>\n                            <option value="MY">\n                                Malaysia (92)\n                            </option>\n                            <option value="PK">\n                                Pakistan (25)\n                            </option>\n                            <option value="CY">\n                                Cyprus (172)\n                            </option>\n                            <option value="NP">\n                                Nepal (15)\n                            </option>\n                            <option value="AT">\n                                Austria (167)\n                            </option>\n                            <option value="BR">\n                                Brazil (148)\n                            </option>\n                            <option value="ES">\n                                Spain (199)\n                            </option>\n                            <option value="CZ">\n                                Czechia (173)\n                            </option>\n                            <option value="LT">\n                                Lithuania (194)\n                            </option>\n                            <option value="CN">\n                                China (161)\n                            </option>\n                            <option value="RS">\n                                Serbia (12)\n                            </option>\n                            <option value="AR">\n                                Argentina (123)\n                            </option>\n                            <option value="CO">\n                                Colombia (137)\n                            </option>\n                            <option value="TH">\n                                Thailand (135)\n                            </option>\n                            <option value="JP">\n                                Japan (115)\n                            </option>\n                            <option value="FR">\n                                France (92)\n                            </option>\n                            <option value="MX">\n                                Mexico (81)\n                            </option>\n                            <option value="NO">\n                                Norway (2)\n                            </option>\n                            <option value="CR">\n                                Costa Rica (81)\n                            </option>\n                            <option value="HU">\n                                Hungary (27)\n                            </option>\n                            <option value="LV">\n                                Latvia (7)\n                            </option>\n                            <option value="PT">\n                                Portugal (5)\n                            </option>\n                            <option value="ZW">\n                                Zimbabwe (21)\n                            </option>\n                            <option value="SI">\n                                Slovenia (3)\n                            </option>\n                            <option value="SC">\n                                Seychelles (10)\n                            </option>\n                            <option value="DO">\n                                Dominican Republic (26)\n                            </option>\n                            <option value="SY">\n                                Syrian Arab Republic (14)\n                            </option>\n                            <option value="VE">\n                                Venezuela (Bolivarian Republic of) (44)\n                            </option>\n                            <option value="KH">\n                                Cambodia (54)\n                            </option>\n                            <option value="SV">\n                                El Salvador (2)\n                            </option>\n                            <option value="FI">\n                                Finland (33)\n                            </option>\n                            <option value="BD">\n                                Bangladesh (166)\n                            </option>\n                            <option value="TR">\n                                Turkiye (84)\n                            </option>\n                            <option value="PE">\n                                Peru (43)\n                            </option>\n                            <option value="TC">\n                                Turks and Caicos Islands (2)\n                            </option>\n                            <option value="BG">\n                                Bulgaria (22)\n                            </option>\n                            <option value="PR">\n                                Puerto Rico (11)\n                            </option>\n                            <option value="CL">\n                                Chile (29)\n                            </option>\n                            <option value="UZ">\n                                Uzbekistan (4)\n                            </option>\n                            <option value="IQ">\n                                Iraq (13)\n                            </option>\n                            <option value="VN">\n                                Viet Nam (86)\n                            </option>\n                            <option value="NZ">\n                                New Zealand (2)\n                            </option>\n                            <option value="PA">\n                                Panama (4)\n                            </option>\n                            <option value="UY">\n                                Uruguay (3)\n                            </option>\n                            <option value="IR">\n                                Iran (Islamic Republic of) (4)\n                            </option>\n                            <option value="DK">\n                                Denmark (4)\n                            </option>\n                            <option value="GT">\n                                Guatemala (12)\n                            </option>\n                            <option value="KE">\n                                Kenya (25)\n                            </option>\n                            <option value="GR">\n                                Greece (5)\n                            </option>\n                            <option value="TT">\n                                Trinidad and Tobago (1)\n                            </option>\n                            <option value="MW">\n                                Malawi (2)\n                            </option>\n                            <option value="KG">\n                                Kyrgyzstan (3)\n                            </option>\n                            <option value="ZM">\n                                Zambia (2)\n                            </option>\n                            <option value="SK">\n                                Slovakia (3)\n                            </option>\n                            <option value="LA">\n                                Lao People&#x27;s Democratic Republic (1)\n                            </option>\n                            <option value="BW">\n                                Botswana (8)\n                            </option>\n                            <option value="HN">\n                                Honduras (18)\n                            </option>\n                            <option value="JM">\n                                Jamaica (2)\n                            </option>\n                            <option value="BS">\n                                Bahamas (1)\n                            </option>\n                            <option value="SA">\n                                Saudi Arabia (6)\n                            </option>\n                            <option value="LY">\n                                Libya (17)\n                            </option>\n                            <option value="NA">\n                                Namibia (3)\n                            </option>\n                            <option value="GD">\n                                Grenada (1)\n                            </option>\n                            <option value="CG">\n                                Congo (3)\n                            </option>\n                            <option value="MN">\n                                Mongolia (8)\n                            </option>\n                            <option value="UG">\n                                Uganda (1)\n                            </option>\n                            <option value="ME">\n                                Montenegro (3)\n                            </option>\n                            <option value="IE">\n                                Ireland (2)\n                            </option>\n                            <option value="BO">\n                                Bolivia (Plurinational State of) (5)\n                            </option>\n                            <option value="PS">\n                                Palestine, State of (10)\n                            </option>\n                            <option value="TZ">\n                                Tanzania, the United Republic of (4)\n                            </option>\n                            <option value="IL">\n                                Israel (2)\n                            </option>\n                            <option value="SN">\n                                Senegal (3)\n                            </option>\n                            <option value="MA">\n                                Morocco (3)\n                            </option>\n                            <option value="LK">\n                                Sri Lanka (1)\n                            </option>\n                            <option value="BY">\n                                Belarus (3)\n                            </option>\n                            <option value="MZ">\n                                Mozambique (1)\n                            </option>\n                            <option value="AZ">\n                                Azerbaijan (4)\n                            </option>\n                            <option value="LB">\n                                Lebanon (1)\n                            </option>\n                            <option value="AM">\n                                Armenia (6)\n                            </option>\n                            <option value="CM">\n                                Cameroon (1)\n                            </option>\n                            <option value="GE">\n                                Georgia (6)\n                            </option>\n                        

In [1]:
from src.proj.util.proxy.finder import FreeProxyFinder
finder = FreeProxyFinder()
finder.find()

Finding proxies through ZDAYEFinder level_type=anonymous
Finding proxies through FreeProxyListCCFinder level_type=anonymous
Finding proxies through FreeProxyWorldFinder level_type=anonymous

ProxySet(n=179)

In [1]:
from src.proj import Proj
from src.data.crawler.announcement.util import fetch_log
fetch_log('abc')

In [3]:
33.95/8/269

0.015776022304832715

In [1]:
from collections import defaultdict

a = defaultdict(bool)
a['a']

False

In [3]:
from src.proj import Logger
from src.proj.util import ScriptTool, ProxyAPI
from src.proj.util.proxy.ppool import AdaptiveProxyPool
from src.data.crawler.announcement.fetcher import FetcherTask, EXCHANGES , EXCHANGE_URLS

pool = ProxyAPI.get_proxy_pool(EXCHANGE_URLS.values(), go_with_cached_proxies=True)

26-04-30 15:55:16|HIGHLIGHT |: Get working proxies for https://www.bse.cn
26-04-30 15:55:16|HIGHLIGHT |: Get working proxies for https://www.sse.com.cn
26-04-30 15:55:16|HIGHLIGHT |: Get working proxies for https://www.szse.cn

In [6]:
pool.proxies

{'https://www.bse.cn': ProxyStatsSetURL(https://www.bse.cn,adaptive,refresh_attempt=0/10),
 'https://www.sse.com.cn': ProxyStatsSetURL(https://www.sse.com.cn,adaptive,refresh_attempt=0/10),
 'https://www.szse.cn': ProxyStatsSetURL(https://www.szse.cn,adaptive,refresh_attempt=0/10)}

In [26]:
import pandas as pd
import numpy as np

from typing import Any


pool = pd.DataFrame({'secid': np.random.randint(0, 1000000, size=50), 
                     'indus': np.random.randint(0, 10, size=50), 
                     'alpha': np.random.randn(50)})

init_port = pd.DataFrame({'secid': np.random.choice(pool['secid'], size=10 , replace = False), 
                          'weight': np.random.randn(10)})

buffer_zone = 0.1
stay_num = 8
no_zone = 0.5
indus_slots = 10
n_best = 10

pool.loc[:, 'ind_rank']  = pool.groupby('indus')['alpha'].rank(method = 'first' , ascending = False)
pool.loc[:, 'rankpct']   = pool['alpha'].rank(pct = True , method = 'first' , ascending = True)

pool = pool.merge(init_port , on = 'secid' , how = 'left').sort_values('alpha' , ascending = False)
pool.loc[:, 'selected'] = pool['weight'].astype(float).fillna(0) > 0
pool.loc[:, 'buffered'] = (
    (pool['rankpct'] >= buffer_zone) + (pool['selected'].cumsum() <= stay_num) * (pool['rankpct'] >= no_zone))

stay = pool.query('selected & buffered')

new_pool = pool.query('(secid not in @stay.secid)').merge(stay.groupby('indus')['secid'].count().rename('ind_count') , on = 'indus' , how = 'left')
entry = new_pool.assign(max_ind_rank = indus_slots - new_pool['ind_count'].fillna(0)).\
    query('ind_rank < max_ind_rank').sort_values('alpha' , ascending = False).head(n_best - stay.shape[0])

df = pd.DataFrame({'secid' : np.union1d(stay['secid'] , entry['secid']) , 'weight' : 1})
df

    secid  weight
0   87026       1
1   92220       1
2  244585       1
3  248610       1
4  404240       1
5  410914       1
6  464663       1
7  725616       1
8  815841       1
9  817782       1

In [24]:
new_pool

,secid_x,indus,alpha,ind_rank,rankpct,weight,selected,buffered,secid_y
0,222493,1,1.625954,1.0,1.00,NaN,False,True,NaN
1,794343,6,1.622298,1.0,0.98,NaN,False,True,NaN
2,922189,5,1.205926,1.0,0.96,NaN,False,True,1.0
3,363937,2,1.099768,1.0,0.94,NaN,False,True,3.0
4,352365,7,1.034912,1.0,0.92,NaN,False,True,NaN
5,327178,3,0.988490,1.0,0.90,NaN,False,True,NaN
6,349928,1,0.641366,2.0,0.86,NaN,False,True,NaN
7,994246,5,0.639826,2.0,0.84,NaN,False,True,1.0
8,466591,3,0.565676,2.0,0.82,NaN,False,True,NaN
9,240698,7,0.544791,2.0,0.80,NaN,False,True,NaN
10,78544,1,0.414343,3.0,0.78,NaN,False,True,NaN
11,476913,3,0.311108,3.0,0.76,NaN,False,True,NaN
12,569792,3,0.241142,4.0,0.74,NaN,False,True,NaN
13,718595,3,0.154712,5.0,0.72,NaN,False,True,NaN
14,430774,1,0.091647,4.0,0.70,-0.323934,False,True,NaN
15,907317,3,0.077229,6.0,0.68,NaN,False,True,NaN
16,966878,3,0.065652,7.0,0.66,-0.951089,False,True,NaN
17,2906,1,0.058243,5.0,0.64,NaN,False,True,NaN
18,107250,8,0.026093,1.0,0.62,NaN,False,True,NaN
19,799136,6,-0.100875,2.0,0.60,NaN,False,True,NaN
20,762059,6,-0.196661,3.0,0.56,NaN,False,True,NaN
21,19731,9,-0.215590,1.0,0.54,NaN,False,True,NaN
22,325421,6,-0.218728,4.0,0.52,NaN,False,True,NaN
23,710296,5,-0.234992,4.0,0.50,NaN,False,True,1.0
24,138306,3,-0.320569,8.0,0.48,NaN,False,True,NaN
25,83000,0,-0.334951,1.0,0.46,NaN,False,True,1.0
26,684272,9,-0.339612,2.0,0.44,NaN,False,True,NaN
27,990619,9,-0.443886,3.0,0.42,NaN,False,True,NaN
28,213317,9,-0.460872,4.0,0.40,NaN,False,True,NaN
29,317845,5,-0.540265,5.0,0.38,NaN,False,True,1.0
30,76869,2,-0.589423,3.0,0.36,NaN,False,True,3.0
31,334305,5,-0.662219,6.0,0.34,NaN,False,True,1.0
32,707303,3,-0.968651,9.0,0.32,NaN,False,True,NaN
33,8026,9,-0.983982,5.0,0.30,NaN,False,True,NaN
34,651936,0,-1.253213,3.0,0.22,NaN,False,True,1.0
35,49484,2,-1.280186,6.0,0.20,NaN,False,True,3.0
36,453316,6,-1.308920,5.0,0.18,NaN,False,True,NaN
37,194880,7,-1.313328,3.0,0.16,NaN,False,True,NaN
38,896918,4,-1.318113,1.0,0.14,NaN,False,True,1.0
39,767582,3,-1.571498,10.0,0.10,NaN,False,True,NaN
40,138653,8,-1.684487,2.0,0.08,NaN,False,False,NaN
41,795623,5,-1.769452,7.0,0.06,NaN,False,False,1.0
42,785718,4,-1.798020,3.0,0.04,-1.383860,False,False,1.0
43,666263,3,-2.958890,11.0,0.02,0.284947,True,False,NaN

In [22]:
stay_ind_count

indus
1    1
2    1
7    2
9    1
Name: secid, dtype: int64

In [6]:
stay

     secid  indus     alpha  ind_rank  rankpct    weight  selected  buffered
22  110039      3  2.126081       1.0     1.00  0.012546      True      True
28  260904      9  1.114042       1.0     0.86  2.828899      True      True
44  629889      1  0.386597       3.0     0.58  1.746981      True      True
45  629889      1  0.386597       3.0     0.58  0.592931      True      True

In [7]:
entry

,secid,indus,alpha,ind_rank,rankpct,weight,selected,buffered,stay_ind_count,max_ind_rank
0,580999,3,1.993092,2.0,0.98,NaN,False,True,1.0,9.0
1,395957,1,1.863609,1.0,0.96,NaN,False,True,2.0,8.0
2,158281,7,1.635280,1.0,0.94,NaN,False,True,NaN,10.0
3,334736,5,1.506816,1.0,0.92,NaN,False,True,NaN,10.0
4,308209,1,1.444555,2.0,0.90,NaN,False,True,2.0,8.0
5,162291,8,1.301753,1.0,0.88,NaN,False,True,NaN,10.0

In [3]:
new_pool

,secid,indus,alpha,ind_rank,rankpct,weight,selected,buffered,stay_ind_count,max_ind_rank
0,709384,4,1.918502,1.0,1.00,NaN,False,True,NaN,10.0
1,905596,5,1.751476,1.0,0.98,NaN,False,True,2.0,8.0
2,798203,2,1.725815,1.0,0.96,NaN,False,True,NaN,10.0
3,893133,2,1.622616,2.0,0.94,NaN,False,True,NaN,10.0
4,693424,7,1.562380,1.0,0.92,NaN,False,True,NaN,10.0
5,31226,5,1.547292,2.0,0.90,NaN,False,True,2.0,8.0
6,988364,4,1.399954,2.0,0.88,NaN,False,True,NaN,10.0
7,902556,8,1.265745,1.0,0.86,NaN,False,True,NaN,10.0
8,147170,9,1.247241,1.0,0.84,NaN,False,True,1.0,9.0
9,203138,8,1.225807,2.0,0.82,NaN,False,True,NaN,10.0
10,100591,0,1.136102,1.0,0.80,NaN,False,True,1.0,9.0
11,497583,5,0.964918,3.0,0.78,NaN,False,True,2.0,8.0
12,479393,0,0.739499,2.0,0.76,-1.601205,False,True,1.0,9.0
13,737798,5,0.721385,4.0,0.74,NaN,False,True,2.0,8.0
14,783307,7,0.647857,2.0,0.70,-1.497492,False,True,NaN,10.0
15,420624,1,0.562957,1.0,0.68,NaN,False,True,NaN,10.0
16,307157,0,0.550911,3.0,0.66,NaN,False,True,1.0,9.0
17,298015,3,0.254858,1.0,0.64,NaN,False,True,NaN,10.0
18,967632,6,0.235417,1.0,0.62,NaN,False,True,NaN,10.0
19,198125,3,0.198419,2.0,0.60,NaN,False,True,NaN,10.0
20,788764,4,0.106113,3.0,0.58,NaN,False,True,NaN,10.0
21,688079,0,0.070758,4.0,0.56,NaN,False,True,1.0,9.0
22,507127,4,0.066508,4.0,0.54,NaN,False,True,NaN,10.0
23,258231,5,0.050390,6.0,0.52,NaN,False,True,2.0,8.0
24,148874,7,-0.072568,3.0,0.50,NaN,False,True,NaN,10.0
25,568303,0,-0.076707,5.0,0.48,NaN,False,True,1.0,9.0
26,788536,7,-0.119250,4.0,0.46,NaN,False,True,NaN,10.0
27,399231,3,-0.165095,3.0,0.44,NaN,False,True,NaN,10.0
28,283327,5,-0.166829,7.0,0.42,NaN,False,True,2.0,8.0
29,498899,1,-0.308666,2.0,0.40,NaN,False,True,NaN,10.0
30,447752,2,-0.349300,3.0,0.38,NaN,False,True,NaN,10.0
31,884877,8,-0.469957,3.0,0.34,NaN,False,True,NaN,10.0
32,758413,8,-0.623778,4.0,0.30,NaN,False,True,NaN,10.0
33,26300,3,-0.684461,4.0,0.26,NaN,False,True,NaN,10.0
34,800490,8,-0.797937,5.0,0.24,NaN,False,True,NaN,10.0
35,461487,1,-0.808923,3.0,0.22,NaN,False,True,NaN,10.0
36,72012,7,-0.884499,5.0,0.20,NaN,False,True,NaN,10.0
37,405529,3,-1.173186,5.0,0.18,NaN,False,True,NaN,10.0
38,971276,1,-1.347812,4.0,0.16,NaN,False,True,NaN,10.0
39,159221,7,-1.518954,6.0,0.14,NaN,False,True,NaN,10.0
40,702602,5,-1.575085,9.0,0.12,-0.172991,False,True,2.0,8.0
41,274682,2,-1.610453,4.0,0.10,NaN,False,True,NaN,10.0
42,932320,0,-1.745601,7.0,0.08,-0.743308,False,False,1.0,9.0
43,961951,7,-1.747305,7.0,0.06,2.064918,True,False,NaN,10.0
44,961951,7,-1.747305,7.0,0.06,0.300403,True,False,NaN,10.0
45,487137,8,-1.824833,6.0,0.04,NaN,False,False,NaN,10.0
46,216188,7,-2.245369,8.0,0.02,NaN,False,False,NaN,10.0

In [24]:
import machineid
machineid.id()

'71A41312-74C2-5E3E-94E3-88261EF3E297'

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************