In [11]:
from src.res.model.util import PredictionModel
model = PredictionModel.SelectModels('gru_day_V1')[0]
model.load_pred(20241231)

       secid  gru_day_V1
0          1    1.126028
1          2    1.253377
2          4    0.986078
3          6    1.044249
4          7    0.795379
...      ...         ...
5176  920978    0.359580
5177  920981    2.206729
5178  920982    0.554663
5179  920985    1.038696
5180  920992    0.164047

[5181 rows x 2 columns]

In [8]:
from src.res.factor.util.classes.universe import Universe
u = Universe('top-1000')
p = u.get(20241231,exclusions = 'loser')

In [9]:
p.item()

Portfolio <date=20241231> <name=top-1000> <value=1>:
       secid  weight
0     601398     1.0
1     300299     1.0
2       2845     1.0
3       2455     1.0
4       2431     1.0
...      ...     ...
4222     899     1.0
4223    2978     1.0
4224  600475     1.0
4225  603227     1.0
4226  300391     1.0

[4227 rows x 2 columns]

In [10]:

p = u.get(20241231)
p.item()

Portfolio <date=20241231> <name=top-1000> <value=1>:
       secid  weight
0     600519     1.0
1     603520     1.0
2       2672     1.0
3       2452     1.0
4     688179     1.0
...      ...     ...
3723     901     1.0
3724  300428     1.0
3725     923     1.0
3726  601609     1.0
3727  300391     1.0

[3728 rows x 2 columns]

In [3]:
import torch
week_rank = torch.floor(T.rank_pct(week_rtn) / 0.05).clip(0,19) 
year_rank = torch.floor(T.rank_pct(year_rtn) / 0.05).clip(0,19) 
next_week_rtn = T.ts_delay(week_rtn , -1)

Beware! future information used!

In [25]:
top_group = (week_rank >= 19).to(torch.float32)
bottom_group = (week_rank <=0).to(torch.float32)

In [ ]:
import pandas as pd
import numpy as np
date = price_block.date[5::5]
top_group = (week_rank - 18).clip(0,1)
d = {
    'secid' : np.repeat(price_block.secid , len(date)) ,
    'date' : np.tile(date , len(price_block.secid)) ,
    'datetime' : pd.to_datetime(np.tile(date , len(price_block.secid)).astype(str) , format = '%Y%m%d') ,
    'year_rtn' : year_rtn.flatten(),
    'week_rank' : week_rank.flatten() ,
    'year_rank' : year_rank.flatten() ,
    'next_week_rtn' : T.ts_delay(week_rtn , -1).flatten() ,
    'next_week_rank' : T.ts_delay(week_rank , -1).flatten() ,
    'cum_weeks' : torch.cumsum(top_group.isfinite() , dim = 1).flatten() ,
    'cum_top_ratio' : (torch.cumsum(top_group.nan_to_num(0) , dim = 1) / torch.cumsum(top_group.isfinite() , dim = 1)).flatten() ,
    'roll_top_ratio': torch.nn.functional.pad(top_group.unfold(1,50,1).nanmean(-1) , (49 , 0) , value = torch.nan).flatten() ,
    'cum_bottom_ratio' : (torch.cumsum(bottom_group.nan_to_num(1) , dim = 1) / torch.cumsum(bottom_group.isfinite() , dim = 1)).flatten() ,
    'roll_bottom_ratio': torch.nn.functional.pad(bottom_group.unfold(1,50,1).nanmean(-1) , (49 , 0) , value = torch.nan).flatten() ,
}

df = pd.DataFrame(d)
df = df.query('date >= 20140101').dropna(how = 'any')
df['loser'] = df.eval('roll_bottom_ratio > 0.02 & roll_top_ratio == 0 & cum_weeks >= 50')
df

Beware! future information used!Beware! future information used!

,secid,date,datetime,year_rtn,week_rank,year_rank,next_week_rtn,next_week_rank,cum_weeks,cum_top_ratio,roll_top_ratio,cum_bottom_ratio,roll_bottom_ratio
415,1,20150724,2015-07-24,0.523878,0.0,8.0,-0.079296,14.0,369,0.043360,0.02,0.060096,0.06
416,1,20150731,2015-07-31,0.386845,14.0,7.0,0.020025,6.0,370,0.043243,0.02,0.059952,0.06
417,1,20150807,2015-08-07,0.339321,6.0,6.0,0.002376,1.0,371,0.043127,0.02,0.059809,0.06
418,1,20150814,2015-08-14,0.376329,1.0,4.0,-0.094519,16.0,372,0.043011,0.02,0.059666,0.06
419,1,20150821,2015-08-21,0.278007,16.0,6.0,-0.060027,16.0,373,0.042895,0.02,0.059524,0.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5016306,920992,20250307,2025-03-07,0.387124,17.0,14.0,0.329981,19.0,115,0.086957,0.08,0.012458,0.08
5016307,920992,20250314,2025-03-14,0.672125,19.0,18.0,-0.222715,0.0,116,0.094828,0.10,0.012443,0.08
5016308,920992,20250321,2025-03-21,0.586147,0.0,17.0,-0.037082,8.0,117,0.094017,0.10,0.013559,0.08
5016309,920992,20250328,2025-03-28,0.516306,8.0,17.0,-0.231512,2.0,118,0.093220,0.10,0.013544,0.08
5016310,920992,20250407,2025-04-07,0.330000,2.0,17.0,0.372722,19.0,119,0.092437,0.10,0.013529,0.08

In [41]:
from src.proj import DB
from src.data import DataBlock
import torch
import numpy as np
import pandas as pd
df_gru = DB.loads('pred' , 'gru_day_V1' , start_dt=20100101 , end_dt = 20991231).drop_duplicates(['secid' , 'date'])
df_gru['value'] = df_gru['gru_day_V1'].where(~df_gru['gru_day_V1'].isna(),df_gru['gru_avg'])
df_gru['rank_pct'] = df_gru.groupby('date')['value'].rank(pct=True)
df_gru['gru_rank'] = np.floor(df_gru['rank_pct'] * 20).clip(0,19)
df_gru = df_gru.loc[:,['date','secid','value','rank_pct','gru_rank']]
df = df.merge(df_gru,on=['date','secid'],how = 'left')
df['top_gru'] = df['gru_rank'] >= 19
df = df.query('~gru_rank.isna()').copy()

In [42]:
df.groupby(['gru_rank'])['next_week_rtn'].agg(['count' , 'mean' , 'std'])

          count      mean       std
gru_rank
0.0       63858 -0.018666  0.106459
1.0       64075 -0.007101  0.086797
2.0       63977 -0.003430  0.079774
3.0       63705 -0.001854  0.075729
4.0       64093 -0.000875  0.072924
5.0       64131 -0.000379  0.070238
6.0       64852 -0.000063  0.069060
7.0       65308  0.000587  0.068439
8.0       65921  0.000945  0.066376
9.0       66720  0.001143  0.065675
10.0      67347  0.001038  0.063504
11.0      67769  0.001369  0.061665
12.0      68698  0.001212  0.060241
13.0      68870  0.001409  0.058485
14.0      69223  0.001783  0.055998
15.0      69403  0.002423  0.054776
16.0      69772  0.002618  0.053591
17.0      70022  0.003480  0.052746
18.0      69879  0.003652  0.052065
19.0      68876  0.004539  0.055171

In [ ]:

coverage = df['loser'].mean()

print(f'coverage is {coverage}')
#stats.reset_index().plot.line('datetime' , 'mean')
df.groupby(['gru_rank','loser'])['next_week_rtn'].agg(['count' , 'mean' , 'std'])

coverage is 0.03633148995996256

                count      mean       std
gru_rank loser
0.0      False  63121 -0.018736  0.106740
         True     737 -0.012672  0.078561
1.0      False  62910 -0.007147  0.087023
         True    1165 -0.004627  0.073556
2.0      False  62641 -0.003473  0.079884
         True    1336 -0.001426  0.074459
3.0      False  62264 -0.001982  0.075880
         True    1441  0.003671  0.068719
4.0      False  62426 -0.000982  0.073021
         True    1667  0.003118  0.069101
5.0      False  62366 -0.000404  0.070403
         True    1765  0.000476  0.064123
6.0      False  62920 -0.000059  0.069195
         True    1932 -0.000178  0.064546
7.0      False  63150  0.000591  0.068487
         True    2158  0.000453  0.067034
8.0      False  63726  0.000931  0.066584
         True    2195  0.001362  0.060027
9.0      False  64321  0.001100  0.065790
         True    2399  0.002292  0.062525
10.0     False  64705  0.001099  0.063629
         True    2642 -0.000475  0.060335
11.0     False  65033  0.001407  0.061811
         True    2736  0.000481  0.058085
12.0     False  65769  0.001313  0.060439
         True    2929 -0.001073  0.055575
13.0     False  65791  0.001435  0.058664
         True    3079  0.000873  0.054526
14.0     False  66040  0.001815  0.056063
         True    3183  0.001133  0.054627
15.0     False  66114  0.002454  0.054902
         True    3289  0.001800  0.052184
16.0     False  66427  0.002670  0.053787
         True    3345  0.001591  0.049523
17.0     False  66573  0.003538  0.052847
         True    3449  0.002366  0.050772
18.0     False  66265  0.003703  0.052272
         True    3614  0.002712  0.048116
19.0     False  65380  0.004629  0.055394
         True    3496  0.002857  0.050812

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************