In [ ]:
from src.res.model.model_module.application import ArchivedPredictorModel
from src.proj import CALENDAR


hd_model = ArchivedPredictorModel.from_model_str('gru_dfl2_new@0@best')
hd_model.hidden_values(CALENDAR.range(20201113,20230606),20230606 , silent = False , print_dates = True , async_save = False)

In [14]:
from collections import defaultdict
from src.res.model.model_module.application import ArchivedPredictorModel
from src.proj import CALENDAR
import numpy as np

tds = CALENDAR.range(20100101,20250625)
test_full_dates = tds[tds >= 20170704]
input_keys_hidden = ['gru_avg@0@best']
model_dates = [20170103,20170207,20170307,20170406,20170505,20170606,20170704,20170801]
for hd_key in input_keys_hidden:
    hd_model = ArchivedPredictorModel.from_model_str(hd_key)
    assert hd_model.model_dates.size > 0 , f'hidden model {hd_key} has no model dates'
    hidden_model_dates : dict[int,list[int]] = defaultdict(list)
    for model_date in model_dates:
        assert hd_model.model_dates[0] <= model_date , f'hidden model {hd_key} has no model date before {model_date}'
        hd_model_date = hd_model.model_dates[hd_model.model_dates <= model_date][-1]
        # fit dates
        model_date_col = (tds < model_date).sum()
        d0 = max(0 , model_date_col - 20 - 480 - 1)
        d1 = max(0 , model_date_col - 20)
        hidden_model_dates[hd_model_date].extend(tds[d0:d1][::5].tolist())
        
        # test dates
        next_model_date = 20171226
        hidden_model_dates[hd_model_date].extend(test_full_dates[(test_full_dates <= next_model_date) & (test_full_dates >= model_date)].tolist())
        
    for hd_model_date , hd_dates in hidden_model_dates.items():
        print(hd_model_date , np.unique(hd_dates))
        # hd_model.hidden_block(list(set(hd_dates)) , hd_model_date)

20170103 [20141215 20141222 20141229 20150107 20150114 20150121 20150128 20150204
 20150211 20150225 20150304 20150311 20150318 20150325 20150401 20150409
 20150416 20150423 20150430 20150508 20150515 20150522 20150529 20150605
 20150612 20150619 20150629 20150706 20150713 20150720 20150727 20150803
 20150810 20150817 20150824 20150831 20150909 20150916 20150923 20150930
 20151014 20151021 20151028 20151104 20151111 20151118 20151125 20151202
 20151209 20151216 20151223 20151230 20160107 20160114 20160121 20160128
 20160204 20160218 20160225 20160303 20160310 20160317 20160324 20160331
 20160408 20160415 20160422 20160429 20160509 20160516 20160523 20160530
 20160606 20160615 20160622 20160629 20160706 20160713 20160720 20160727
 20160803 20160810 20160817 20160824 20160831 20160907 20160914 20160923
 20160930 20161014 20161021 20161028 20161104 20161111 20161118 20161125
 20161202 20161209 20161216 20161223 20161230 20170109 20170116 20170123
 20170206 20170213 20170220 20170227 20170306 20170313 20170320 20170327
 20170405 20170412 20170419 20170426 20170504 20170704 20170705 20170706
 20170707 20170710 20170711 20170712 20170713 20170714 20170717 20170718
 20170719 20170720 20170721 20170724 20170725 20170726 20170727 20170728
 20170731 20170801 20170802 20170803 20170804 20170807 20170808 20170809
 20170810 20170811 20170814 20170815 20170816 20170817 20170818 20170821
 20170822 20170823 20170824 20170825 20170828 20170829 20170830 20170831
 20170901 20170904 20170905 20170906 20170907 20170908 20170911 20170912
 20170913 20170914 20170915 20170918 20170919 20170920 20170921 20170922
 20170925 20170926 20170927 20170928 20170929 20171009 20171010 20171011
 20171012 20171013 20171016 20171017 20171018 20171019 20171020 20171023
 20171024 20171025 20171026 20171027 20171030 20171031 20171101 20171102
 20171103 20171106 20171107 20171108 20171109 20171110 20171113 20171114
 20171115 20171116 20171117 20171120 20171121 20171122 20171123 20171124
 20171127 20171128 20171129 20171130 20171201 20171204 20171205 20171206
 20171207 20171208 20171211 20171212 20171213 20171214 20171215 20171218
 20171219 20171220 20171221 20171222 20171225 20171226]
20170704 [20150612 20150619 20150629 20150706 20150713 20150720 20150727 20150803
 20150810 20150817 20150824 20150831 20150909 20150916 20150923 20150930
 20151014 20151021 20151028 20151104 20151111 20151118 20151125 20151202
 20151209 20151216 20151223 20151230 20160107 20160114 20160121 20160128
 20160204 20160218 20160225 20160303 20160310 20160317 20160324 20160331
 20160408 20160415 20160422 20160429 20160509 20160516 20160523 20160530
 20160606 20160615 20160622 20160629 20160706 20160713 20160720 20160727
 20160803 20160810 20160817 20160824 20160831 20160907 20160914 20160923
 20160930 20161014 20161021 20161028 20161104 20161111 20161118 20161125
 20161202 20161209 20161216 20161223 20161230 20170109 20170116 20170123
 20170206 20170213 20170220 20170227 20170306 20170313 20170320 20170327
 20170405 20170412 20170419 20170426 20170504 20170511 20170518 20170525
 20170605 20170612 20170619 20170626 20170703 20170704 20170705 20170706
 20170707 20170710 20170711 20170712 20170713 20170714 20170717 20170718
 20170719 20170720 20170721 20170724 20170725 20170726 20170727 20170728
 20170731 20170801 20170802 20170803 20170804 20170807 20170808 20170809
 20170810 20170811 20170814 20170815 20170816 20170817 20170818 20170821
 20170822 20170823 20170824 20170825 20170828 20170829 20170830 20170831
 20170901 20170904 20170905 20170906 20170907 20170908 20170911 20170912
 20170913 20170914 20170915 20170918 20170919 20170920 20170921 20170922
 20170925 20170926 20170927 20170928 20170929 20171009 20171010 20171011
 20171012 20171013 20171016 20171017 20171018 20171019 20171020 20171023
 20171024 20171025 20171026 20171027 20171030 20171031 20171101 20171102
 20171103 20171106 20171107 20171108 20171109 20171110 20171113 20171114
 20171115 20171116 20171117 20171120 20171121 20171122 20171123 20171124
 20171127 20171128 20171129 20171130 20171201 20171204 20171205 20171206
 20171207 20171208 20171211 20171212 20171213 20171214 20171215 20171218
 20171219 20171220 20171221 20171222 20171225 20171226]

In [1]:
from src.res.factor.defs.stock.level1.behavior.momentum_umr_new import umr_new_1m
calc = umr_new_1m()
calc.calc_factor(20250417)

       secid  umr_new_1m
0          1   -0.630720
1          2   -0.024960
2          4   -0.801290
3          6   -3.143363
4          7   -0.235815
...      ...         ...
5407  920978    0.274420
5408  920981   -0.851699
5409  920982   -0.320251
5410  920985    0.432419
5411  920992   -0.959732

[5412 rows x 2 columns]

In [ ]:
from src.api.calls.research import CarryOutScheduleWorkList
CarryOutScheduleWorkList._is_schedule_created_recently('gru_30m_new')

False

In [ ]:
from src.api.calls.research import CarryOutScheduleWorkList
CarryOutScheduleWorkList.get_schedules()

['gru_30m_new']

In [1]:
from src.res.model.model_module.application import ArchivedPredictorModel 
from src.res.model.util import PredictorPath
path = PredictorPath.SelectModels('gru_day_V0')[0]
model = ArchivedPredictorModel(path)

In [ ]:
from src.api.pkgs.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************