In [3]:
from src.data.download.tushare.task.t00_info import Description
cal = Description()
cal.update_dates([20260321])

  --> description Overwritten : /Users/mengkjin/workspace/learndl/data/DataBase/DB_information_ts/description.feather

[20260321]

In [157]:
from src.data.preprocess.preprocessor import BaseTypePreProcessor , BlockLoader ,DataBlock
import numpy as np
import torch

class PrePro_week(BaseTypePreProcessor):
    WEEKDAYS = 5
    def block_loaders(self) -> dict[str,BlockLoader]: 
        return {'day':BlockLoader('trade_ts', 'day', ['adjfactor', 'preclose', *self.TRADE_FEAT])}
    def final_feat(self): return self.TRADE_FEAT
    def load_blocks(self , start_dt = None , end_dt = None , secid_align = None , date_align = None , indent = 0 , vb_level = 1 , **kwargs):
        if start_dt is not None and start_dt < 0: 
            start_dt = 2 * start_dt
        blocks : dict[str,DataBlock] = {}
        for src_key , loader in self.block_loaders().items():
            blocks[src_key] = loader.load(start_dt , end_dt , indent = indent + 1 , vb_level = vb_level + 1 , **kwargs).align(secid_align , date_align , inplace = True)
            secid_align = blocks[src_key].secid
            date_align  = blocks[src_key].date
        return blocks
    
    def process(self , blocks): 
        data_block = blocks['day'].adjust_price()

        new_values = np.full(np.multiply(data_block.shape,(1, 1, self.WEEKDAYS, 1)),np.nan)
        for i in range(self.WEEKDAYS): 
            new_values[:,self.WEEKDAYS-1-i:,i] = data_block.values[:,:len(data_block.date)-self.WEEKDAYS+1+i,0]
        data_block.update(values = new_values)
        data_block = data_block.adjust_price(adjfactor = False , divide=data_block.loc(inday = 0,feature = 'preclose'))
        return data_block

pro = PrePro_week()
blocks = pro.load_blocks(20200101 , 20241231)

  --> Timer(trade_ts blocks reading 1 DataBase) start ...
    --> Timer(trade_ts blocks reading [day] DataBase) finished! Cost <1 Sec
  --> Timer(trade_ts blocks reading 1 DataBase) finished! Cost <1 Sec

In [158]:
blocks.feature

AttributeError: 'dict' object has no attribute 'feature'

In [3]:
data_block = blocks['day'].adjust_price()
WEEKDAYS = 5

new_values = np.full(np.multiply(data_block.shape,(1, 1, WEEKDAYS, 1)),np.nan)

In [159]:
from src.data.preprocess.preprocessor import BaseTypePreProcessor , BlockLoader , DataBlock
from src.res.model.data_module.module import DataModule
block = DataBlock.load_preprocess('week')

In [161]:
block.inday

array([0, 1, 2, 3, 4])

In [185]:
tuple(range(1,2))

(1,)

In [ ]:
import torch
v = block.values
v.shape
from typing import Callable

def rolling_rotation(x : torch.Tensor , index0 : torch.Tensor , index1 : torch.Tensor , seqlen : int , step = 1 , dim = 1 , squeeze_out = True) -> torch.Tensor:
    '''rotate [stock , date , inday , feature] to [sample , rolling , inday , feature]'''
    assert x.ndim == 4 , x.ndim
    assert len(index0) == len(index1) , (index0 , index1)
    assert index1.max() < x.shape[dim] , (index1.max() , x.shape)
    assert index1.min() >= seqlen * step - 1 , (index1.min() , seqlen , step)
    
    try:
        start = max(0 , index1.min().item() - seqlen * step + 1)
        end = min(x.shape[dim] , index1.max().item() + 1)
        new_index1 = index1 - start + 1 - seqlen * step
        new_x = x[:,start:end].unfold(dim , seqlen * step , 1)[index0 , new_index1].\
            permute(0,3,1,2)[:,step-1::step] # [stock , seqlen (by step) , inday , feature]
    except MemoryError:
        new_x = torch.stack([x[index0 , index1 + (i + 1 - seqlen) * step] for i in range(seqlen)],dim=dim)
    
    assert new_x.shape[1] == seqlen , (new_x.shape[1] , seqlen)
    if squeeze_out: 
        new_x = new_x.squeeze(-2)
    return new_x

def finite_position(data : torch.Tensor , index1 : torch.Tensor | None = None , 
                    seqlen : int = 1 , step : int = 1 , endpoint_nonzero = False , x_all_valid = True):
    '''return finite position (with shape of len(index[0]) * step_len) the first 2 dims'''
    if index1 is None: 
        index1 = torch.arange(data.shape[1])
    assert data.ndim > 2 , data.ndim
    sum_dim = tuple(range(2,data.ndim))
    agg = data.sum(sum_dim).isfinite()
    print(agg.shape)
    if seqlen * step > 1:
        agg = torch.nn.functional.pad(agg, (seqlen * step - 1,0) , value = False)
        print(agg.shape)
    try:
        predicate : Callable[...,torch.Tensor] = torch.all if x_all_valid else torch.any
        valid = predicate(agg.unfold(1,seqlen*step,1)[...,step-1::step],-1)[:,index1]
    except MemoryError:
        predicate = torch.multiply if x_all_valid else torch.add
        valid = torch.full_like((agg[:,:len(index1)]), x_all_valid)
        for i in range(seqlen):
            valid = predicate(valid , agg[:,index1 + i * step])
    if endpoint_nonzero: 
        valid *= data[:,index1].not_equal(0).all(sum_dim)     
    return valid


index0 = torch.arange(v.shape[0])
index1 = torch.ones_like(index0) * v.shape[1] - 1

week0 = rolling_rotation(v , index0 , index1 , 50 , 5 , 1 , True)

In [184]:
week0[0]

tensor([[[1.0714e+03, 1.0656e+03, 1.0784e+03, 1.0609e+03, 1.0690e+03,
          3.3724e-01],
         [1.0644e+03, 1.0621e+03, 1.0703e+03, 1.0586e+03, 1.0632e+03,
          3.3190e-01],
         [1.0633e+03, 1.0539e+03, 1.0679e+03, 1.0539e+03, 1.0609e+03,
          3.6878e-01],
         [1.0516e+03, 1.0703e+03, 1.0726e+03, 1.0492e+03, 1.0620e+03,
          5.2410e-01],
         [1.0726e+03, 1.0738e+03, 1.0831e+03, 1.0633e+03, 1.0735e+03,
          5.1823e-01]],

        [[1.0714e+03, 1.0726e+03, 1.0738e+03, 1.0668e+03, 1.0703e+03,
          2.1333e-01],
         [1.0726e+03, 1.0621e+03, 1.0738e+03, 1.0586e+03, 1.0634e+03,
          2.7925e-01],
         [1.0621e+03, 1.0644e+03, 1.0656e+03, 1.0528e+03, 1.0589e+03,
          3.3059e-01],
         [1.0633e+03, 1.1029e+03, 1.1053e+03, 1.0598e+03, 1.0889e+03,
          8.5625e-01],
         [1.0994e+03, 1.0959e+03, 1.1064e+03, 1.0913e+03, 1.0979e+03,
          4.4000e-01]],

        [[1.0959e+03, 1.0749e+03, 1.0994e+03, 1.0749e+03, 1.0839e+03,
          5.9693e-01],
         [1.0726e+03, 1.0738e+03, 1.0761e+03, 1.0679e+03, 1.0718e+03,
          3.7804e-01],
         [1.0726e+03, 1.0633e+03, 1.0726e+03, 1.0598e+03, 1.0635e+03,
          4.4533e-01],
         [1.0621e+03, 1.0819e+03, 1.1018e+03, 1.0586e+03, 1.0857e+03,
          1.0263e+00],
         [1.0773e+03, 1.0679e+03, 1.0854e+03, 1.0633e+03, 1.0712e+03,
          5.7775e-01]],

        ...,

        [[1.4861e+03, 1.4912e+03, 1.4976e+03, 1.4810e+03, 1.4891e+03,
          4.9680e-01],
         [1.5206e+03, 1.5066e+03, 1.5270e+03, 1.5015e+03, 1.5117e+03,
          1.1171e+00],
         [1.5066e+03, 1.4989e+03, 1.5117e+03, 1.4976e+03, 1.5032e+03,
          4.9867e-01],
         [1.4989e+03, 1.5142e+03, 1.5168e+03, 1.4964e+03, 1.5082e+03,
          5.0822e-01],
         [1.5066e+03, 1.4772e+03, 1.5079e+03, 1.4772e+03, 1.4888e+03,
          6.9248e-01]],

        [[1.4772e+03, 1.4785e+03, 1.4900e+03, 1.4734e+03, 1.4817e+03,
          4.1520e-01],
         [1.4785e+03, 1.4734e+03, 1.4887e+03, 1.4721e+03, 1.4803e+03,
          4.1334e-01],
         [1.4797e+03, 1.4887e+03, 1.5002e+03, 1.4785e+03, 1.4911e+03,
          5.2386e-01],
         [1.4810e+03, 1.4810e+03, 1.4874e+03, 1.4746e+03, 1.4814e+03,
          3.5937e-01],
         [1.4810e+03, 1.4849e+03, 1.4951e+03, 1.4797e+03, 1.4867e+03,
          3.6827e-01]],

        [[1.4874e+03, 1.4989e+03, 1.5130e+03, 1.4874e+03, 1.5043e+03,
          8.5512e-01],
         [1.4976e+03, 1.5155e+03, 1.5168e+03, 1.4976e+03, 1.5095e+03,
          6.9611e-01],
         [1.5155e+03, 1.5232e+03, 1.5360e+03, 1.5130e+03, 1.5244e+03,
          7.6024e-01],
         [1.5232e+03, 1.5155e+03, 1.5245e+03, 1.5053e+03, 1.5125e+03,
          5.1535e-01],
         [1.5168e+03, 1.5117e+03, 1.5206e+03, 1.4900e+03, 1.5041e+03,
          6.6476e-01]]])

In [175]:
valid = finite_position(v , seqlen = 50 , step = 5)

torch.Size([5614, 4373])
torch.Size([5614, 4622])

In [178]:
valid.shape , v.shape

(torch.Size([5614, 4373]), torch.Size([5614, 4373, 5, 6]))

In [4]:
from src.res.model.util.config import ModelConfig
from src.api import ModelAPI
import shutil
models = ModelAPI.available_models(True , True)
for model in models:
    config = ModelConfig(model , stage = 2 , resume = 1 , selection = 0)
    config.base_path.conf_file('algo').unlink(missing_ok = True)
    shutil.rmtree(config.base_path.conf('model') , ignore_errors = True)
    shutil.rmtree(config.base_path.conf('param') , ignore_errors = True)

In [8]:
from pathlib import Path
p = Path('/Users/mengkjin/workspace/learndl/models/st/nn@gru@gru_week/configs')

In [1]:
from src.res.model.util.config import ModelConfig
config = ModelConfig('st@nn@resnet_gru@gru_week')

In [2]:
config.input_data_prenorm

{'day': {'divlast': True, 'histnorm': True}, 'week': {'channelnorm': True}}

In [2]:
config.Param

{'callbacks.BatchDisplay': {},
 'callbacks.CallbackTimer': {},
 'callbacks.DetailedAlphaAnalysis': {},
 'callbacks.EarlyExitRetrain': {'earliest': 10,
                                'lr_multiplier': [1, 0.1, 10, 0.01, 100, 1],
                                'max_attempt': 4},
 'callbacks.EarlyStoppage': {'patience': 20},
 'callbacks.NanLossRetrain': {'max_attempt': 4},
 'callbacks.ResetOptimizer': {'num_reset': 2,
                              'recover_level': 1.0,
                              'speedup2x': True,
                              'trigger': 40},
 'callbacks.StatusDisplay': {},
 'callbacks.SummaryWriter': {},
 'callbacks.ValidationConverge': {'eps': 1e-05, 'patience': 5},
 'conditional.short_test.callbacks.DetailedAlphaAnalysis': {'tasks': ['factor',
                                                                      't50']},
 'conditional.short_test.input.data.types': 'day',
 'conditional.short_test.input.filter.date': '20200101-20250331',
 'conditional.short_test.input.filter.secid': 'random.200',
 'conditional.short_test.model.beg_date': 20241101,
 'conditional.short_test.model.end_date': 20250331,
 'conditional.short_test.model.window': 240,
 'conditional.short_test.train.max_epoch': 3,
 'conditional.transformer.callbacks.ResetOptimizer': {'num_reset': 1,
                                                      'recover_level': 1.0,
                                                      'speedup2x': True,
                                                      'trigger': 60},
 'env.allow_tf32': True,
 'env.detect_anomaly': False,
 'env.mem_storage': True,
 'env.precision': 'float',
 'env.random_seed': None,
 'env.short_test': True,
 'input.combo.types': ['data', 'factor'],
 'input.data.prenorm.day.divlast': True,
 'input.data.prenorm.day.histnorm': True,
 'input.data.types': '30m',
 'input.factor.types.fundament': ['quality'],
 'input.filter.date': None,
 'input.filter.secid': None,
 'input.hidden.types': ['gru_day_V0.0.best', 'gru_day_V0.1.best'],
 'input.sequence.lens': {'30m': 30,
                         'day': 30,
                         'factor': 1,
                         'hidden': 1,
                         'indus': 30,
                         'style': 30},
 'input.sequence.steps': {'data': 1, 'day': 1, 'factor': 1, 'hidden': 1},
 'input.type': 'data',
 'model.beg_date': 20170103,
 'model.end_date': 99991231,
 'model.interval': None,
 'model.interval.boost': 20,
 'model.interval.nn': 120,
 'model.labels': ['std_lag1_10'],
 'model.module': 'nn@gru',
 'model.module.boost': 'xgboost',
 'model.module.boost.optuna': False,
 'model.module.boost.optuna.trials': 10,
 'model.module.factor': None,
 'model.module.nn': 'gru',
 'model.module.nn.boost_head': False,
 'model.module.nn.boost_head.boost': 'lgbm',
 'model.name': None,
 'model.submodels': ['best'],
 'model.window': None,
 'model.window.boost': 240,
 'model.window.nn': 2400,
 'train.batch_size': 10000,
 'train.callbacks': ['StatusDisplay',
                     'SummaryWriter',
                     'BasicTestResult',
                     'DetailedAlphaAnalysis',
                     'EarlyStoppage',
                     'EarlyExitRetrain',
                     'NanLossRetrain',
                     'ValidationConverge'],
 'train.criterion.accuracy': {'spearman': {'which_label': [0],
                                           'which_output': [0]}},
 'train.criterion.loss.ccc_hcorr.lamb': 0.01,
 'train.criterion.multilosses': {'name': 'hybrid',
                                 'params': {'dwa': {'tau': 2},
                                            'ewa': {},
                                            'gls': {},
                                            'hybrid': {'phi': None, 'tau': 2},
                                            'ruw': {'phi': None},
                                            'rws': {}}},
 'train.criterion.weight.fit': 'equal',
 'train.criterion.weight.test': 'equal',
 'train.dataloader.sample_method': 'sequential',
 'train.dataloader.shuffle_option': 'epoch',
 'train.dataloader.train_ratio': 0.8,
 'train.fitting_step': 5,
 'train.max_epoch': 200,
 'train.skip_horizon': 20,
 'train.trainer.gradient.clip_value': 10.0,
 'train.trainer.learn_rate.base': 0.005,
 'train.trainer.learn_rate.transfer_multiplier.decoder': 1.0,
 'train.trainer.learn_rate.transfer_multiplier.encoder': 0.1,
 'train.trainer.optimizer.name': 'Adam',
 'train.trainer.optimizer.param': {},
 'train.trainer.scheduler.name': 'cycle',
 'train.trainer.scheduler.param.base_lr': 1e-07,
 'train.trainer.scheduler.param.step_size_up': 4,
 'train.trainer.transfer': False}

In [4]:
from src.res.model.model_module.application import ModelCalculator

calc = ModelCalculator('gru@gru_avg')
calc(20241213)

BatchData(input=BatchInput(x=tensor([[[-1.3656e-01, -3.4077e-02, -1.3469e-01, -1.2340e-01, -1.1457e-01,
          -3.7856e-01],
         [-1.5811e-01,  6.1276e-02, -4.6180e-02, -6.3696e-02, -2.3191e-02,
          -1.4315e-01],
         [-5.4606e-02,  9.3822e-03, -5.7149e-02, -1.8845e-02, -2.4513e-02,
          -2.4323e-01],
         ...,
         [ 9.9078e-03,  2.7259e-01,  5.0484e-02,  2.9587e-01,  2.0563e-01,
          -6.3920e-01],
         [-1.5036e-01,  7.1207e-01,  2.1807e-01,  4.0788e-01,  4.5367e-01,
          -7.1451e-01],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
          -8.1852e-02]],

        [[ 4.2424e-01,  4.6481e-01,  4.1923e-01,  3.5978e-01,  3.7690e-01,
          -2.7611e-01],
         [ 3.3095e-01,  6.5460e-01,  5.9131e-01,  4.4826e-01,  5.8923e-01,
           1.2210e-02],
         [ 5.1696e-01,  7.7169e-01,  7.7667e-01,  5.2517e-01,  6.8634e-01,
           3.4659e-01],
         ...,
         [-1.8728e-01,  5.6482e-01,  3.9078e-01,  2.5427e-01,  4.8837e-01,
          -6.1944e-01],
         [ 1.5166e-01,  9.6239e-01,  4.5539e-01,  5.6701e-01,  7.7805e-01,
          -8.3579e-01],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
           1.5006e-01]],

        [[-6.7425e-01, -3.8722e-01, -3.9751e-01, -5.8505e-01, -5.3108e-01,
          -6.3285e-01],
         [-3.8021e-01, -1.5350e-01, -2.4756e-01, -3.2059e-01, -3.0909e-01,
          -6.1041e-01],
         [-1.7099e-01, -1.4584e-01, -1.7060e-01, -1.3792e-01, -1.7693e-01,
          -6.6493e-01],
         ...,
         [-2.0090e+00, -1.9770e+00, -2.8171e+00, -1.7509e+00, -2.3364e+00,
          -1.4803e+00],
         [-2.5919e+00, -8.3470e-02, -1.3355e+00, -2.2548e+00, -7.7943e-01,
          -1.3446e+00],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
           2.4556e-01]],

        ...,

        [[-7.0246e-02, -7.3907e-02, -2.0177e-01, -1.2582e-01, -1.6253e-01,
          -2.4274e-01],
         [ 1.2013e-01,  1.9425e-01,  8.6393e-02,  1.6522e-01,  1.2121e-01,
           1.5860e-01],
         [ 3.8679e-01,  3.5638e-01,  3.7879e-01,  4.5978e-01,  3.5771e-01,
           3.5534e-01],
         ...,
         [ 4.0827e-01, -7.1407e-01, -4.5133e-01, -8.8651e-02, -6.6732e-01,
          -5.5132e-01],
         [-4.2685e-01, -7.1944e-01, -1.5969e+00, -5.9703e-01, -1.4120e+00,
          -8.1758e-01],
         [ 5.7177e-02,  5.7178e-02,  5.7215e-02,  5.7140e-02,  5.7179e-02,
           2.1827e-01]],

        [[-6.4627e-01, -7.5660e-01, -8.9494e-01, -5.8935e-01, -8.1059e-01,
          -5.7402e-01],
         [-2.4330e-01, -3.9898e-01, -5.2322e-01, -2.7105e-01, -4.5810e-01,
          -4.1798e-01],
         [ 1.4043e-01,  1.8365e-02, -5.5420e-02,  3.7968e-02, -5.0209e-02,
          -1.5029e-01],
         ...,
         [-4.3200e-01, -2.2617e+00, -2.4575e+00, -4.4776e-01, -1.9393e+00,
          -1.2188e+00],
         [-1.2522e+00, -2.5451e+00, -3.8033e+00, -1.8773e+00, -3.5722e+00,
          -1.3780e+00],
         [ 0.0000e+00,  0.0000e+00,  5.7215e-02,  0.0000e+00,  0.0000e+00,
           2.4556e-01]],

        [[-8.2435e-01, -5.9190e-01, -7.5081e-01, -8.7221e-01, -7.8233e-01,
           2.9619e-03],
         [-4.9025e-01, -2.9783e-01, -4.1982e-01, -4.5624e-01, -4.0655e-01,
           4.1860e-01],
         [ 2.1782e-01, -5.4877e-02, -5.2498e-02, -1.6716e-01, -6.9956e-02,
           1.2305e+00],
         ...,
         [ 1.1694e+00, -5.6889e-01, -6.9186e-02, -6.3055e-02, -2.1198e-01,
           4.6345e-02],
         [-1.6898e-01, -5.3050e-02, -1.2469e+00, -1.5797e+00, -1.6423e+00,
           2.5848e-01],
         [ 0.0000e+00, -5.7178e-02, -5.7215e-02,  0.0000e+00, -5.7179e-02,
           2.3191e-01]]], device='mps:0'), y=tensor([[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]], device='mps:0'), w=None, i=tensor([[   0,   38],
        [   1,   38],
        [   2,   38],
        ...,
        [5542,   38],
        [5543,   38],
        [5544,   38]], device='mps:0'), valid=tensor([True, True, True,  ..., True, True, True], device='mps:0'), kwargs={}), output=BatchOutput(outputs=(tensor([[ 0.8483],
        [-0.2334],
        [-1.1192],
        ...,
        [-0.3721],
        [-0.2400],
        [-0.3133]], device='mps:0', grad_fn=<CatBackward0>), {'hidden': tensor([[-0.0709,  0.2944,  0.0050,  ..., -0.2303,  0.2847,  0.1345],
        [ 1.5227, -0.8635, -0.0444,  ...,  0.9613, -0.7736, -0.8312],
        [ 2.8161, -1.7795, -0.0923,  ...,  1.9938, -1.6412, -1.6858],
        ...,
        [ 1.7260, -1.0025, -0.0445,  ...,  1.1256, -0.9026, -0.9602],
        [ 1.5362, -0.8792, -0.0428,  ...,  0.9713, -0.7736, -0.8471],
        [ 1.6323, -0.9234, -0.0568,  ...,  1.0554, -0.8452, -0.9207]],
       device='mps:0', grad_fn=<LinearBackward0>)})))

In [11]:
from src.res.model.util import PredictionModel
model = PredictionModel.SelectModels('gru_day_V1')[0]
model.load_pred(20241231)

       secid  gru_day_V1
0          1    1.126028
1          2    1.253377
2          4    0.986078
3          6    1.044249
4          7    0.795379
...      ...         ...
5176  920978    0.359580
5177  920981    2.206729
5178  920982    0.554663
5179  920985    1.038696
5180  920992    0.164047

[5181 rows x 2 columns]

In [8]:
from src.res.factor.util.classes.universe import Universe
u = Universe('top-1000')
p = u.get(20241231,exclusions = 'loser')

In [1]:
from src.data.update.custom.week_rank_loser import WeekRankLoserUpdater
WeekRankLoserUpdater.update_all('update')

    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100104.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100105.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100106.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100107.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100108.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100111.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100112.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100113.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100114.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100115.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100118.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100119.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100120.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100121.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100122.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100125.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100126.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100127.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100128.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100129.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100201.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100202.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100203.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100204.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100205.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100208.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100209.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100210.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100211.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100212.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100222.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100223.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100224.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100225.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100226.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100301.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100302.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100303.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100304.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100305.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100308.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100309.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100310.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100311.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100312.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100315.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100316.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100317.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100318.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100319.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100322.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100323.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100324.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100325.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100326.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100329.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100330.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100331.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100401.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100402.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100406.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100407.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100408.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100409.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100412.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100413.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100414.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100415.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100416.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100419.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100420.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100421.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100422.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100423.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100426.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100427.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100428.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100429.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100430.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100504.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100505.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100506.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100507.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100510.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100511.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100512.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100513.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100514.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100517.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100518.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100519.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100520.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100521.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100524.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100525.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100526.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100527.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100528.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100531.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100601.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100602.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100603.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100604.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100607.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100608.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100609.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100610.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100611.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100617.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100618.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100621.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100622.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100623.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100624.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100625.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100628.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100629.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100630.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100701.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100702.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100705.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100706.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100707.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100708.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100709.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100712.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100713.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100714.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100715.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100716.feather
    --> week_rank_loser File Created: /Users/mengkjin/workspace/learndl/data/DataBase/DB_exposure/week_rank_loser/2010/week_rank_loser.20100719.feather

In [ ]:
from src.proj import PATH
paths = []
for p in PATH.result.rglob('*.tar'):
    p.unlink()
    
for p in PATH.model.rglob('*.tar'):
    p.unlink()

paths

[PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest1/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest5/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest2/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest3/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest4/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/ht_master_combined.backtest/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/use_daily.backtest/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/df_scores_v0.backtest/account.tar'),
 PosixPath('/Users/mengkjin/workspace/learndl/results/trade/backtest/gru_day_V1.backtest/account.tar')]

In [ ]:
from datetime import datetime , time
from zoneinfo import ZoneInfo
beijing_tz = ZoneInfo("Asia/Shanghai")
datetime.now().astimezone().tzinfo , datetime.now(beijing_tz).astimezone().tzinfo

AttributeError: 'datetime.timezone' object has no attribute 'key'

In [11]:
datetime.today() , datetime.now()

(datetime.datetime(2026, 3, 16, 9, 45, 20, 374246),
 datetime.datetime(2026, 3, 16, 9, 45, 20, 374307))

In [7]:
datetime.now(beijing_tz)

datetime.datetime(2026, 3, 16, 21, 43, 27, 737842, tzinfo=zoneinfo.ZoneInfo(key='Asia/Shanghai'))

In [1]:
from src.res.factor.util.classes.alpha_model import CompositeAlpha
alpha = CompositeAlpha(['sellside@huatai.master_combined@master_combined', 'factor@df_scores_v0', 'gru_day_V1'])
af = alpha.get(20241231)
af.item().to_dataframe()

       secid     alpha
0          1  1.483658
1          2  0.863664
2          4 -0.986211
3          6  0.542467
4          7 -0.121362
...      ...       ...
5224  920978 -0.164427
5225  920981  1.397860
5226  920982 -0.019465
5227  920985 -0.246272
5228  920992 -1.209771

[5229 rows x 2 columns]

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************