In [167]:
from src.data import DataBlock

block = DataBlock.load_raw('trade_ts' , 'day' , 20070101 , 20991231).adjust_price().align_feature(['close'])

In [ ]:
import src.func.tensor as T
import torch
from torch.nn.functional import pad
pctchg = T.pctchg(block.values.squeeze() , 1)
logrtn = torch.log(pctchg + 1)
week_rtn = pad(logrtn.unfold(1 , 5 , 1).sum(-1) , (4 , 0) , value = torch.nan)[:,5::5]
year_rtn = pad(logrtn.unfold(1 , 250 , 1).sum(-1) , (249 , 0) , value = torch.nan)[:,5::5]
week_rtn.shape , year_rtn.shape

(torch.Size([5649, 888]), torch.Size([5649, 888]))

In [209]:
import torch
week_rank = torch.floor(T.rank_pct(week_rtn) / 0.05).clip(0,19) 
year_rank = torch.floor(T.rank_pct(year_rtn) / 0.05).clip(0,19)

In [ ]:
import pandas as pd
import numpy as np
date = block.date[5::5]
top_group = (week_rank - 18).clip(0,1)
d = {
    'secid' : np.repeat(block.secid , len(date)) ,
    'date' : np.tile(date , len(block.secid)) ,
    'datetime' : pd.to_datetime(np.tile(date , len(block.secid)).astype(str) , format = '%Y%m%d') ,
    'year_rtn' : year_rtn.flatten(),
    'week_rank' : week_rank.flatten() ,
    'year_rank' : year_rank.flatten() ,
    'cum_weeks' : torch.cumsum(top_group.isfinite() , dim = 1).flatten() ,
    'cum_top_ratio' : (torch.cumsum(top_group.nan_to_num(0) , dim = 1) / torch.cumsum(top_group.isfinite() , dim = 1)).flatten() ,
    'roll_top_ratio': torch.nn.functional.pad(top_group.unfold(1,50,1).nanmean(-1) , (49 , 0) , value = torch.nan).flatten() ,
    'next_top_chance' : torch.nn.functional.pad(top_group[:,1:].unfold(1,4,1).nansum(-1) , (0 , 4) , value = torch.nan).flatten() 
}
df = pd.DataFrame(d)
df = df.query('date >= 20140101').dropna(how = 'any')
df['low_cum_ratio'] = np.floor(df.cum_top_ratio * 100)
df['low_roll_ratio'] = np.floor(df.roll_top_ratio * 100)
df

,secid,date,year_rtn,week_rank,year_rank,cum_weeks,cum_top_ratio,roll_top_ratio,next_top_chance,low_cum_ratio,low_roll_ratio
415,1,20150724,0.523878,0.0,8.0,369,0.043360,0.02,0.0,4.0,2.0
416,1,20150731,0.386845,14.0,7.0,370,0.043243,0.02,0.0,4.0,2.0
417,1,20150807,0.339321,6.0,6.0,371,0.043127,0.02,0.0,4.0,2.0
418,1,20150814,0.376329,1.0,4.0,372,0.043011,0.02,0.0,4.0,2.0
419,1,20150821,0.278007,16.0,6.0,373,0.042895,0.02,0.0,4.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
5016303,920992,20250214,-0.007694,18.0,7.0,112,0.089286,0.08,1.0,8.0,8.0
5016304,920992,20250221,0.243734,5.0,10.0,113,0.088496,0.08,1.0,8.0,8.0
5016305,920992,20250228,0.371807,8.0,12.0,114,0.087719,0.08,1.0,8.0,8.0
5016306,920992,20250307,0.387124,17.0,14.0,115,0.086957,0.08,1.0,8.0,8.0
5016307,920992,20250314,0.672125,19.0,18.0,116,0.094828,0.10,1.0,9.0,10.0

In [224]:
df0 = df.query('low_cum_ratio <= 3 & low_roll_ratio <= 1 & cum_weeks >= 100')
coverage = len(df0) / len(df)

average = df0['next_top_chance'].mean()
print(f'coverage is {coverage} , chance is {average}')
stats = df0.groupby(['date'])['next_top_chance'].agg(['count' , 'mean' , 'std'])
#stats.reset_index().plot.line('datetime' , 'mean')
df0.groupby(['year_rank'])['next_top_chance'].agg(['count' , 'mean' , 'std'])

coverage is 0.11101119200379678 , chance is 0.0895700752735138

           count      mean       std
year_rank
0.0         4349  0.134054  0.379696
1.0         6891  0.109128  0.345390
2.0         8842  0.099186  0.336992
3.0        10409  0.095206  0.326667
4.0        11338  0.083877  0.301599
5.0        11917  0.086515  0.312786
6.0        12125  0.085113  0.308004
7.0        12191  0.088426  0.310954
8.0        12264  0.075016  0.290234
9.0        11959  0.083954  0.302428
10.0       11290  0.083791  0.307973
11.0       10733  0.083574  0.310404
12.0        9531  0.089288  0.318545
13.0        8273  0.088843  0.320500
14.0        6781  0.087745  0.321040
15.0        5631  0.088972  0.317188
16.0        4153  0.092945  0.325581
17.0        2441  0.100778  0.320865
18.0        1024  0.125977  0.354760
19.0         189  0.185185  0.402905

In [199]:
df0

          count      mean       std   datetime
date
20090204      1  1.000000       NaN 2009-02-04
20090211      5  0.400000  0.547723 2009-02-11
20090218     14  0.142857  0.363137 2009-02-18
20090225     23  0.217391  0.421741 2009-02-25
20090304     37  0.162162  0.373684 2009-03-04
...         ...       ...       ...        ...
20250214    535  0.059813  0.287329 2025-02-14
20250221    581  0.077453  0.309378 2025-02-21
20250228    607  0.082372  0.314347 2025-02-28
20250307    607  0.118616  0.362107 2025-03-07
20250314    607  0.115321  0.353967 2025-03-14

[784 rows x 4 columns]

In [130]:
df1 = df.query('low_roll_ratio <= 1 & cum_weeks >= 500')
coverage = len(df1) / len(df)
print(f'coverage is {coverage}')
df1.groupby(['low_roll_ratio'])['next_top_chance'].agg(['count' , 'mean' , 'std'])

coverage is 0.056665383887428526

                 count      mean       std
low_roll_ratio
0.0             152989  0.072077  0.280606

                  count      mean       std
low_ratio_group
0.0              119370  0.114895  0.348327
1.0              119475  0.098472  0.329743
2.0              267127  0.122923  0.367330
3.0              407556  0.143131  0.395583
4.0              462184  0.165672  0.423428
5.0              419469  0.188262  0.452079
6.0              328756  0.207783  0.471300
7.0              218682  0.223512  0.487989
8.0              134536  0.240798  0.504848
9.0               84678  0.252108  0.513272
10.0              61786  0.263474  0.526054
11.0              41322  0.274962  0.535153
12.0              29211  0.285817  0.539844
13.0              20690  0.281634  0.537983
14.0              15541  0.313172  0.562148
15.0              12011  0.323370  0.570729
16.0              10832  0.339273  0.586382
17.0               6404  0.356184  0.597844
18.0               5996  0.341895  0.587486
19.0               2895  0.357513  0.585170
20.0               6430  0.365319  0.595893

In [68]:
cum_top_ratio[cum_weeks[:,-1] > 50][:,-1].nan_to_num(0).max()

tensor(0.2237)

In [69]:
cum_top_ratio[cum_weeks[:,-1] > 50][:,-1].nan_to_num(1).min()

tensor(0.)

In [7]:
block.values[0]

tensor([[[2.5015e+01, 3.6647e+02, 3.8323e+02,  ..., 3.5567e+00,
          4.9105e+00, 6.1647e+00]],

        [[2.5015e+01, 3.4846e+02, 3.4846e+02,  ..., 2.7614e+00,
          3.8126e+00, 4.7863e+00]],

        [[2.5015e+01, 3.2645e+02, 3.3870e+02,  ..., 1.6323e+00,
          2.2536e+00, 2.8292e+00]],

        ...,

        [[1.2778e+02, 1.3967e+03, 1.4069e+03,  ..., 4.3431e-01,
          4.3432e-01, 9.7992e-01]],

        [[1.2778e+02, 1.3992e+03, 1.4158e+03,  ..., 4.2457e-01,
          4.2458e-01, 9.5794e-01]],

        [[1.2778e+02, 1.4107e+03, 1.4299e+03,  ..., 3.7468e-01,
          3.7469e-01, 8.4537e-01]]])

In [ ]:
from src.api.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************