In [2]:
from src.res.model.model_module.application import ArchivedPredictorModel
from src.proj import CALENDAR


hd_model = ArchivedPredictorModel.from_model_str('gru_dfl2_new@0@best')
hd_model.hidden_values(CALENDAR.range(20201113,20230606),20230606 , silent = False , print_dates = True , async_save = False)

ArchivedPredictorModel >> Model gru_dfl2_new Hiddens of Model Date 20230606 has 622 dates awaiting
  --> Dates: 20201113~20230606(622days)
2026-06-27 02:18:35.531826 start_date: 20201113 , end_date: 20230606
2026-06-27 02:18:35.533380 load data for gru_dfl2_new with use_data: both
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load start ...
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load finished! Cost 0.0001 Sec
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load_blocks start ...
    --> y dumped loading start ...

Project Verbosity Changed from 3 to 10

    --> y dumped loading finished! Cost 0.2667 Sec
    --> y blocks loading start ...
      --> labels_ts blocks reading 2 DataBase start ...
        --> labels_ts blocks reading [ret10_lag] DataBase start ...
        --> labels_ts blocks reading [ret10_lag] DataBase finished! Cost 0.1500 Sec
        --> labels_ts blocks reading [ret20_lag] DataBase start ...
        --> labels_ts blocks reading [ret20_lag] DataBase finished! Cost 0.1184 Sec
      --> labels_ts blocks reading 2 DataBase finished! Cost 0.2690 Sec
      --> labels_ts blocks merging (2) start ...
      --> labels_ts blocks merging (2) finished! Cost 0.0074 Sec
      --> models blocks reading 1 DataBase start ...
        --> models blocks reading [tushare_cne5_exp] DataBase start ...
        --> models blocks reading [tushare_cne5_exp] DataBase finished! Cost 0.4026 Sec
      --> models blocks reading 1 DataBase finished! Cost 0.4030 Sec
    --> y blocks loading finished! Cost 0.7012 Sec
    --> y blocks process start ...
    --> y blocks process finished! Cost 0.3288 Sec
    --> y blocks masking start ...
    --> y blocks masking finished! Cost 0.1982 Sec
    --> y blocks merging start ...
    --> y blocks merging finished! Cost 0.3832 Sec
    --> dfl2 dumped loading start ...
    --> dfl2 dumped loading finished! Cost 2.7415 Sec
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load_blocks finished! Cost 7.9580 Sec
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> align_blocks start ...
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> align_blocks finished! Cost 2.2636 Sec
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load_norms start ...
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load_norms finished! Cost 0.0017 Sec
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load_factor start ...
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> load_factor finished! Cost 0.0000 Sec
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> blocks_ffill start ...
  --> <src.data.util.classes.module_data.ModuleData object at 0x7a708c2c23c0> blocks_ffill finished! Cost 3 Min 1.9012 Sec
DataModule >> Data loaded, shape: {'x': {'dfl2': torch.Size([5699, 4732, 1, 100])}, 'y': torch.Size([5699, 4732, 1, 1]), 'secid': (5699,), 'date': (4732,)}

Project Verbosity Changed from 10 to 3

2026-06-27 02:21:47.942731 self.data.use_data: both
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_kwargs start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_kwargs finished! Cost 0.0017 Sec
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_inputs start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_inputs finished! Cost 0.0000 Sec
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 1 start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 1 finished! Cost 0.0001 Sec
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 2 start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 2 finished! Cost 2 Min 2.3069 Sec
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 3 start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 3 finished! Cost 0.0001 Sec
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 4 start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 4 finished! Cost 0.0221 Sec
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 5 start ...
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static 5 finished! Cost 4.9551 Sec
DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606)) setup_loader_static finished! Cost 2 Min 7.6271 Sec
2026-06-27 02:23:55.572204 self.data.loader_param: DataloaderParam(stage='retrospective', model_date=20230606, seqlens={'dfl2': 30}, retro_start_date=np.int64(20201113), retro_end_date=np.int64(20230606))
  --> **gru_dfl2_new Hidden Values File Created: /home/mengkjin/workspace/learndl/models/nn/gru@gru_dfl2_new/snapshot/hidden_values/0.20230606.best.feather

shape: (2_293_395, 66)
┌────────┬──────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ secid  ┆ date     ┆ hidden.0  ┆ hidden.1 ┆ … ┆ hidden.60 ┆ hidden.61 ┆ hidden.62 ┆ hidden.63 │
│ ---    ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64    ┆ i64      ┆ f32       ┆ f32      ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32       │
╞════════╪══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1      ┆ 20201113 ┆ -0.044127 ┆ 0.183943 ┆ … ┆ -0.170637 ┆ -0.094984 ┆ -0.18934  ┆ -1.931571 │
│ 2      ┆ 20201113 ┆ -0.046269 ┆ 0.179902 ┆ … ┆ -0.174731 ┆ -0.088279 ┆ -0.166162 ┆ -2.580895 │
│ 4      ┆ 20201113 ┆ -0.11992  ┆ 0.126106 ┆ … ┆ -0.185826 ┆ -0.057042 ┆ -0.045408 ┆ 0.838152  │
│ 5      ┆ 20201113 ┆ -0.036325 ┆ 0.178407 ┆ … ┆ -0.183049 ┆ -0.080606 ┆ -0.154053 ┆ -1.642166 │
│ 6      ┆ 20201113 ┆ -0.081654 ┆ 0.133051 ┆ … ┆ -0.165055 ┆ -0.081967 ┆ -0.106772 ┆ 1.341325  │
│ …      ┆ …        ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 688799 ┆ 20230606 ┆ -0.046283 ┆ 0.16403  ┆ … ┆ -0.18656  ┆ -0.08526  ┆ -0.149576 ┆ -2.999241 │
│ 688800 ┆ 20230606 ┆ -0.064199 ┆ 0.13208  ┆ … ┆ -0.188522 ┆ -0.086484 ┆ -0.098763 ┆ -3.748951 │
│ 688819 ┆ 20230606 ┆ -0.046193 ┆ 0.173748 ┆ … ┆ -0.189635 ┆ -0.08453  ┆ -0.146348 ┆ -3.202133 │
│ 688981 ┆ 20230606 ┆ -0.049973 ┆ 0.173775 ┆ … ┆ -0.178921 ┆ -0.081813 ┆ -0.159033 ┆ -3.318563 │
│ 689009 ┆ 20230606 ┆ -0.104525 ┆ 0.138038 ┆ … ┆ -0.159531 ┆ -0.09993  ┆ -0.040744 ┆ 0.36074   │
└────────┴──────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [1]:
from src.res.factor.defs.stock.level1.behavior.momentum_umr_new import umr_new_1m
calc = umr_new_1m()
calc.calc_factor(20250417)

       secid  umr_new_1m
0          1   -0.630720
1          2   -0.024960
2          4   -0.801290
3          6   -3.143363
4          7   -0.235815
...      ...         ...
5407  920978    0.274420
5408  920981   -0.851699
5409  920982   -0.320251
5410  920985    0.432419
5411  920992   -0.959732

[5412 rows x 2 columns]

In [ ]:
from src.api.calls.research import CarryOutScheduleWorkList
CarryOutScheduleWorkList._is_schedule_created_recently('gru_30m_new')

False

In [ ]:
from src.api.calls.research import CarryOutScheduleWorkList
CarryOutScheduleWorkList.get_schedules()

['gru_30m_new']

In [1]:
from src.res.model.model_module.application import ArchivedPredictorModel 
from src.res.model.util import PredictorPath
path = PredictorPath.SelectModels('gru_day_V0')[0]
model = ArchivedPredictorModel(path)

In [ ]:
from src.api.pkgs.summary import SummaryAPI
SummaryAPI.update()

*************************************************** Summary Start at 2026-02-06 00:16:20 ***************************************************
Summary of Account Period Return:

              gru_avg                       gru_day                      df_scores_v0                     ht_master_combined
                t50       scr       rev       t50       scr       rev        t50         scr       rev           t50            scr       rev
StartDate     20170104  20170104  20170104  20170104  20170104  20170104   20191218    20191218  20191218      20180102       20180102  20180102
EndDate       20250107  20250107  20250107  20250107  20250107  20250107   20241219    20241219  20241219      20241219       20241219  20241219
Total            8.222     9.697     9.122     8.149     8.549     8.725      4.663       2.594     4.145        10.017          6.495    13.378
Annualized       0.319     0.344     0.335     0.318     0.325     0.328      0.413       0.291     0.387         0.411          0.335     0.466
Y2017            0.469     0.545     0.526     0.457     0.503     0.429        NaN         NaN       NaN           NaN            NaN       NaN
Y2018            0.397     0.588     0.548     0.293     0.612     0.428        NaN         NaN       NaN         0.435          0.667     0.882
Y2019            0.437     0.488     0.549     0.611     0.426     0.612      0.011        0.02     0.032         0.811          0.509     0.739
Y2020            0.649      0.44     0.396     0.737     0.481     0.584       0.54       0.666     0.633          0.63          0.512     0.593
Y2021             0.19     0.285     0.295      0.27     0.285     0.339      0.881       0.374     0.607         0.581          0.319     0.477
Y2022            0.173     0.126     0.106     0.074     0.113       0.1      0.212       0.189     0.277         0.086           0.07     0.102
Y2023            0.125     0.141     0.137     0.032      0.09     0.069       0.31       0.169     0.215          0.17          0.113     0.162
Y2024            0.268     0.306     0.289     0.297     0.281     0.258      0.218       0.107     0.225         0.294          0.256     0.458
Y2025           -0.047    -0.057    -0.055     -0.05    -0.065    -0.059        NaN         NaN       NaN           NaN            NaN       NaN
Last Week       -0.047    -0.057    -0.055     -0.05    -0.065    -0.059     -0.024      -0.024    -0.027        -0.027         -0.026    -0.024
Last Month      -0.038    -0.077     -0.08     -0.06      -0.1    -0.083      0.063      -0.008     0.055         0.054         -0.003     0.065
Last Quarter    -0.037    -0.005    -0.022     0.016    -0.047    -0.026       0.32       0.187     0.295         0.376          0.188     0.405
Last Year         0.21     0.224     0.213     0.233      0.19       0.2      0.227       0.109     0.231         0.287          0.268     0.456

******************************************** Summary Finish at 2026-02-06 00:16:21, Cost <1 Sec ********************************************